/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateLicenseKeyResponse {
    /// Business ID
    #[serde(rename = "business_id")]
    pub business_id: String,
    /// Creation timestamp
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Limited customer details associated with the license key.
    #[serde(rename = "customer")]
    pub customer: Box<models::CustomerLimitedDetailsResponse>,
    /// License key instance ID
    #[serde(rename = "id")]
    pub id: String,
    /// Associated license key ID
    #[serde(rename = "license_key_id")]
    pub license_key_id: String,
    /// Instance name
    #[serde(rename = "name")]
    pub name: String,
    /// Related product info. Present if the license key is tied to a product.
    #[serde(rename = "product")]
    pub product: Box<models::ActivateLicenseKeyProductInfo>,
}

impl ActivateLicenseKeyResponse {
    pub fn new(business_id: String, created_at: String, customer: models::CustomerLimitedDetailsResponse, id: String, license_key_id: String, name: String, product: models::ActivateLicenseKeyProductInfo) -> ActivateLicenseKeyResponse {
        ActivateLicenseKeyResponse {
            business_id,
            created_at,
            customer: Box::new(customer),
            id,
            license_key_id,
            name,
            product: Box::new(product),
        }
    }
}

