/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateLicenseKeyRequest {
    #[serde(rename = "license_key")]
    pub license_key: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl ActivateLicenseKeyRequest {
    pub fn new(license_key: String, name: String) -> ActivateLicenseKeyRequest {
        ActivateLicenseKeyRequest {
            license_key,
            name,
        }
    }
}

