/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivateLicenseKeyProductInfo {
    /// Name of the product, if set by the merchant.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Unique identifier for the product.
    #[serde(rename = "product_id")]
    pub product_id: String,
}

impl ActivateLicenseKeyProductInfo {
    pub fn new(product_id: String) -> ActivateLicenseKeyProductInfo {
        ActivateLicenseKeyProductInfo {
            name: None,
            product_id,
        }
    }
}

