/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddMeterToPrice {
    /// Optional credit entitlement ID to link this meter to for credit-based billing
    #[serde(rename = "credit_entitlement_id", skip_serializing_if = "Option::is_none")]
    pub credit_entitlement_id: Option<String>,
    /// Meter description. Will ignored on Request, but will be shown in response
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "free_threshold", skip_serializing_if = "Option::is_none")]
    pub free_threshold: Option<i64>,
    /// Meter measurement unit. Will ignored on Request, but will be shown in response
    #[serde(rename = "measurement_unit", skip_serializing_if = "Option::is_none")]
    pub measurement_unit: Option<String>,
    #[serde(rename = "meter_id")]
    pub meter_id: String,
    /// Number of meter units that equal one credit. Required when credit_entitlement_id is set.
    #[serde(rename = "meter_units_per_credit", skip_serializing_if = "Option::is_none")]
    pub meter_units_per_credit: Option<String>,
    /// Meter name. Will ignored on Request, but will be shown in response
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The price per unit in lowest denomination. Must be greater than zero. Supports up to 5 digits before decimal point and 12 decimal places.
    #[serde(rename = "price_per_unit", skip_serializing_if = "Option::is_none")]
    pub price_per_unit: Option<String>,
}

impl AddMeterToPrice {
    pub fn new(meter_id: String) -> AddMeterToPrice {
        AddMeterToPrice {
            credit_entitlement_id: None,
            description: None,
            free_threshold: None,
            measurement_unit: None,
            meter_id,
            meter_units_per_credit: None,
            name: None,
            price_per_unit: None,
        }
    }
}

