/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddProductsToGroupRequest {
    /// Products to add to the group
    #[serde(rename = "products")]
    pub products: Vec<models::GroupProduct>,
}

impl AddProductsToGroupRequest {
    pub fn new(products: Vec<models::GroupProduct>) -> AddProductsToGroupRequest {
        AddProductsToGroupRequest {
            products,
        }
    }
}

