/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddonResponse {
    /// Unique identifier for the business to which the addon belongs.
    #[serde(rename = "business_id")]
    pub business_id: String,
    /// Created time
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Currency of the Addon
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    /// Optional description of the Addon
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// id of the Addon
    #[serde(rename = "id")]
    pub id: String,
    /// Image of the Addon
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Name of the Addon
    #[serde(rename = "name")]
    pub name: String,
    /// Amount of the addon
    #[serde(rename = "price")]
    pub price: i32,
    /// Tax category applied to this Addon
    #[serde(rename = "tax_category")]
    pub tax_category: models::TaxCategory,
    /// Updated time
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl AddonResponse {
    pub fn new(business_id: String, created_at: String, currency: models::Currency, id: String, name: String, price: i32, tax_category: models::TaxCategory, updated_at: String) -> AddonResponse {
        AddonResponse {
            business_id,
            created_at,
            currency,
            description: None,
            id,
            image: None,
            name,
            price,
            tax_category,
            updated_at,
        }
    }
}

