/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachAddonReq {
    #[serde(rename = "addon_id")]
    pub addon_id: String,
    #[serde(rename = "quantity")]
    pub quantity: i32,
}

impl AttachAddonReq {
    pub fn new(addon_id: String, quantity: i32) -> AttachAddonReq {
        AttachAddonReq {
            addon_id,
            quantity,
        }
    }
}

