/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachExistingCustomer {
    #[serde(rename = "customer_id")]
    pub customer_id: String,
}

impl AttachExistingCustomer {
    pub fn new(customer_id: String) -> AttachExistingCustomer {
        AttachExistingCustomer {
            customer_id,
        }
    }
}

