/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AttachCreditEntitlementRequest : Request struct for attaching a credit entitlement to a product
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachCreditEntitlementRequest {
    /// ID of the credit entitlement to attach
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    /// Number of credits to grant when this product is purchased
    #[serde(rename = "credits_amount")]
    pub credits_amount: String,
    /// Currency for credit-related pricing
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
    /// Number of days after which credits expire
    #[serde(rename = "expires_after_days", skip_serializing_if = "Option::is_none")]
    pub expires_after_days: Option<i32>,
    /// Balance threshold percentage for low balance notifications (0-100)
    #[serde(rename = "low_balance_threshold_percent", skip_serializing_if = "Option::is_none")]
    pub low_balance_threshold_percent: Option<i32>,
    /// Maximum number of rollover cycles allowed
    #[serde(rename = "max_rollover_count", skip_serializing_if = "Option::is_none")]
    pub max_rollover_count: Option<i32>,
    /// Controls how overage is handled at billing cycle end.
    #[serde(rename = "overage_behavior", skip_serializing_if = "Option::is_none")]
    pub overage_behavior: Option<models::CbbOverageBehavior>,
    /// Whether overage usage is allowed beyond credit balance
    #[serde(rename = "overage_enabled", skip_serializing_if = "Option::is_none")]
    pub overage_enabled: Option<bool>,
    /// Maximum amount of overage allowed
    #[serde(rename = "overage_limit", skip_serializing_if = "Option::is_none")]
    pub overage_limit: Option<String>,
    /// Price per credit unit for purchasing additional credits
    #[serde(rename = "price_per_unit", skip_serializing_if = "Option::is_none")]
    pub price_per_unit: Option<String>,
    /// Proration behavior for credit grants during plan changes
    #[serde(rename = "proration_behavior", skip_serializing_if = "Option::is_none")]
    pub proration_behavior: Option<models::CbbProrationBehavior>,
    /// Whether unused credits can roll over to the next billing period
    #[serde(rename = "rollover_enabled", skip_serializing_if = "Option::is_none")]
    pub rollover_enabled: Option<bool>,
    /// Percentage of unused credits that can roll over (0-100)
    #[serde(rename = "rollover_percentage", skip_serializing_if = "Option::is_none")]
    pub rollover_percentage: Option<i32>,
    /// Number of timeframe units for rollover window
    #[serde(rename = "rollover_timeframe_count", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_count: Option<i32>,
    /// Time interval for rollover window (day, week, month, year)
    #[serde(rename = "rollover_timeframe_interval", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_interval: Option<models::TimeInterval>,
    /// Credits granted during trial period
    #[serde(rename = "trial_credits", skip_serializing_if = "Option::is_none")]
    pub trial_credits: Option<String>,
    /// Whether trial credits expire when trial ends
    #[serde(rename = "trial_credits_expire_after_trial", skip_serializing_if = "Option::is_none")]
    pub trial_credits_expire_after_trial: Option<bool>,
}

impl AttachCreditEntitlementRequest {
    /// Request struct for attaching a credit entitlement to a product
    pub fn new(credit_entitlement_id: String, credits_amount: String) -> AttachCreditEntitlementRequest {
        AttachCreditEntitlementRequest {
            credit_entitlement_id,
            credits_amount,
            currency: None,
            expires_after_days: None,
            low_balance_threshold_percent: None,
            max_rollover_count: None,
            overage_behavior: None,
            overage_enabled: None,
            overage_limit: None,
            price_per_unit: None,
            proration_behavior: None,
            rollover_enabled: None,
            rollover_percentage: None,
            rollover_timeframe_count: None,
            rollover_timeframe_interval: None,
            trial_credits: None,
            trial_credits_expire_after_trial: None,
        }
    }
}

