/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BrandVerificationStatus {
    #[serde(rename = "Success")]
    Success,
    #[serde(rename = "Fail")]
    Fail,
    #[serde(rename = "Review")]
    Review,
    #[serde(rename = "Hold")]
    Hold,

}

impl std::fmt::Display for BrandVerificationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Success => write!(f, "Success"),
            Self::Fail => write!(f, "Fail"),
            Self::Review => write!(f, "Review"),
            Self::Hold => write!(f, "Hold"),
        }
    }
}

impl Default for BrandVerificationStatus {
    fn default() -> BrandVerificationStatus {
        Self::Success
    }
}

