/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CalculatedAddonItem {
    #[serde(rename = "addon_id")]
    pub addon_id: String,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "discount_amount", skip_serializing_if = "Option::is_none")]
    pub discount_amount: Option<i32>,
    #[serde(rename = "discounted_price")]
    pub discounted_price: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "og_currency")]
    pub og_currency: models::Currency,
    #[serde(rename = "og_price")]
    pub og_price: i32,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<i32>,
    #[serde(rename = "tax_category")]
    pub tax_category: models::TaxCategory,
    #[serde(rename = "tax_inclusive")]
    pub tax_inclusive: bool,
    #[serde(rename = "tax_rate")]
    pub tax_rate: i32,
}

impl CalculatedAddonItem {
    pub fn new(addon_id: String, currency: models::Currency, discounted_price: i32, name: String, og_currency: models::Currency, og_price: i32, quantity: i32, tax_category: models::TaxCategory, tax_inclusive: bool, tax_rate: i32) -> CalculatedAddonItem {
        CalculatedAddonItem {
            addon_id,
            currency,
            description: None,
            discount_amount: None,
            discounted_price,
            name,
            og_currency,
            og_price,
            quantity,
            tax: None,
            tax_category,
            tax_inclusive,
            tax_rate,
        }
    }
}

