/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CbbLedgerTransactionType {
    #[serde(rename = "credit_added")]
    CreditAdded,
    #[serde(rename = "credit_deducted")]
    CreditDeducted,
    #[serde(rename = "credit_expired")]
    CreditExpired,
    #[serde(rename = "credit_rolled_over")]
    CreditRolledOver,
    #[serde(rename = "rollover_forfeited")]
    RolloverForfeited,
    #[serde(rename = "overage_charged")]
    OverageCharged,
    #[serde(rename = "auto_top_up")]
    AutoTopUp,
    #[serde(rename = "manual_adjustment")]
    ManualAdjustment,
    #[serde(rename = "refund")]
    Refund,

}

impl std::fmt::Display for CbbLedgerTransactionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreditAdded => write!(f, "credit_added"),
            Self::CreditDeducted => write!(f, "credit_deducted"),
            Self::CreditExpired => write!(f, "credit_expired"),
            Self::CreditRolledOver => write!(f, "credit_rolled_over"),
            Self::RolloverForfeited => write!(f, "rollover_forfeited"),
            Self::OverageCharged => write!(f, "overage_charged"),
            Self::AutoTopUp => write!(f, "auto_top_up"),
            Self::ManualAdjustment => write!(f, "manual_adjustment"),
            Self::Refund => write!(f, "refund"),
        }
    }
}

impl Default for CbbLedgerTransactionType {
    fn default() -> CbbLedgerTransactionType {
        Self::CreditAdded
    }
}

