/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CbbProrationBehavior {
    #[serde(rename = "prorate")]
    Prorate,
    #[serde(rename = "no_prorate")]
    NoProrate,

}

impl std::fmt::Display for CbbProrationBehavior {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Prorate => write!(f, "prorate"),
            Self::NoProrate => write!(f, "no_prorate"),
        }
    }
}

impl Default for CbbProrationBehavior {
    fn default() -> CbbProrationBehavior {
        Self::Prorate
    }
}

