/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CbbGrantSourceType {
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "one_time")]
    OneTime,
    #[serde(rename = "addon")]
    Addon,
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "rollover")]
    Rollover,

}

impl std::fmt::Display for CbbGrantSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Subscription => write!(f, "subscription"),
            Self::OneTime => write!(f, "one_time"),
            Self::Addon => write!(f, "addon"),
            Self::Api => write!(f, "api"),
            Self::Rollover => write!(f, "rollover"),
        }
    }
}

impl Default for CbbGrantSourceType {
    fn default() -> CbbGrantSourceType {
        Self::Subscription
    }
}

