/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangePlanPreviewResponse {
    #[serde(rename = "immediate_charge")]
    pub immediate_charge: Box<models::ImmediateCharge>,
    #[serde(rename = "new_plan")]
    pub new_plan: Box<models::SubscriptionResponse>,
}

impl ChangePlanPreviewResponse {
    pub fn new(immediate_charge: models::ImmediateCharge, new_plan: models::SubscriptionResponse) -> ChangePlanPreviewResponse {
        ChangePlanPreviewResponse {
            immediate_charge: Box::new(immediate_charge),
            new_plan: Box::new(new_plan),
        }
    }
}

