/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CheckoutCreditEntitlementItem : Minimal credit entitlement info shown at checkout — what credits the customer will receive
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutCreditEntitlementItem {
    /// ID of the credit entitlement
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    /// Name of the credit entitlement
    #[serde(rename = "credit_entitlement_name")]
    pub credit_entitlement_name: String,
    /// Unit label (e.g. \"API Calls\", \"Tokens\")
    #[serde(rename = "credit_entitlement_unit")]
    pub credit_entitlement_unit: String,
    /// Number of credits granted
    #[serde(rename = "credits_amount")]
    pub credits_amount: String,
}

impl CheckoutCreditEntitlementItem {
    /// Minimal credit entitlement info shown at checkout — what credits the customer will receive
    pub fn new(credit_entitlement_id: String, credit_entitlement_name: String, credit_entitlement_unit: String, credits_amount: String) -> CheckoutCreditEntitlementItem {
        CheckoutCreditEntitlementItem {
            credit_entitlement_id,
            credit_entitlement_name,
            credit_entitlement_unit,
            credits_amount,
        }
    }
}

