/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckoutSessionCustomization {
    /// Force the checkout interface to render in a specific language (e.g. `en`, `es`)
    #[serde(rename = "force_language", skip_serializing_if = "Option::is_none")]
    pub force_language: Option<String>,
    /// Show on demand tag  Default is true
    #[serde(rename = "show_on_demand_tag", skip_serializing_if = "Option::is_none")]
    pub show_on_demand_tag: Option<bool>,
    /// Show order details by default  Default is true
    #[serde(rename = "show_order_details", skip_serializing_if = "Option::is_none")]
    pub show_order_details: Option<bool>,
    /// Theme of the page (determines which mode - light/dark/system - to use)  Default is `System`.
    #[serde(rename = "theme", skip_serializing_if = "Option::is_none")]
    pub theme: Option<models::ThemeMode>,
    /// Optional custom theme configuration with colors for light and dark modes
    #[serde(rename = "theme_config", skip_serializing_if = "Option::is_none")]
    pub theme_config: Option<Box<models::ThemeConfig>>,
}

impl CheckoutSessionCustomization {
    pub fn new() -> CheckoutSessionCustomization {
        CheckoutSessionCustomization {
            force_language: None,
            show_on_demand_tag: None,
            show_order_details: None,
            theme: None,
            theme_config: None,
        }
    }
}

