/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateShortLinkRequest {
    /// Slug for the short link.
    #[serde(rename = "slug")]
    pub slug: String,
    /// Static Checkout URL parameters to apply to the resulting short URL.
    #[serde(rename = "static_checkout_params", skip_serializing_if = "Option::is_none")]
    pub static_checkout_params: Option<std::collections::HashMap<String, String>>,
}

impl CreateShortLinkRequest {
    pub fn new(slug: String) -> CreateShortLinkRequest {
        CreateShortLinkRequest {
            slug,
            static_checkout_params: None,
        }
    }
}

