/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEntitlementRequest {
    /// Optional description
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Platform-specific configuration (validated per integration_type)
    #[serde(rename = "integration_config")]
    pub integration_config: Box<models::IntegrationConfig>,
    /// Which platform integration this entitlement uses
    #[serde(rename = "integration_type")]
    pub integration_type: models::EntitlementIntegrationType,
    /// Additional metadata for the entitlement
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    /// Display name for this entitlement
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateEntitlementRequest {
    pub fn new(
        integration_config: models::IntegrationConfig,
        integration_type: models::EntitlementIntegrationType,
        name: String,
    ) -> CreateEntitlementRequest {
        CreateEntitlementRequest {
            description: None,
            integration_config: Box::new(integration_config),
            integration_type,
            metadata: None,
            name,
        }
    }
}
