/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAddonRequest {
    /// The currency of the Addon
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    /// Optional description of the Addon
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name of the Addon
    #[serde(rename = "name")]
    pub name: String,
    /// Amount of the addon
    #[serde(rename = "price")]
    pub price: i32,
    /// Tax category applied to this Addon
    #[serde(rename = "tax_category")]
    pub tax_category: models::TaxCategory,
}

impl CreateAddonRequest {
    pub fn new(currency: models::Currency, name: String, price: i32, tax_category: models::TaxCategory) -> CreateAddonRequest {
        CreateAddonRequest {
            currency,
            description: None,
            name,
            price,
            tax_category,
        }
    }
}

