/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMeterRequest {
    /// Aggregation configuration for the meter
    #[serde(rename = "aggregation")]
    pub aggregation: Box<models::MeterAggregation>,
    /// Optional description of the meter
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Event name to track
    #[serde(rename = "event_name")]
    pub event_name: String,
    /// Optional filter to apply to the meter
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::MeterFilter>>,
    /// measurement unit
    #[serde(rename = "measurement_unit")]
    pub measurement_unit: String,
    /// Name of the meter
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateMeterRequest {
    pub fn new(aggregation: models::MeterAggregation, event_name: String, measurement_unit: String, name: String) -> CreateMeterRequest {
        CreateMeterRequest {
            aggregation: Box::new(aggregation),
            description: None,
            event_name,
            filter: None,
            measurement_unit,
            name,
        }
    }
}

