/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSubscriptionChargeResponse {
    #[serde(rename = "payment_id")]
    pub payment_id: String,
}

impl CreateSubscriptionChargeResponse {
    pub fn new(payment_id: String) -> CreateSubscriptionChargeResponse {
        CreateSubscriptionChargeResponse {
            payment_id,
        }
    }
}

