/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Create the webhook in a disabled state.  Default is false
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// Filter events to the webhook.  Webhook event will only be sent for events in the list.
    #[serde(rename = "filter_types", skip_serializing_if = "Option::is_none")]
    pub filter_types: Option<Vec<models::EventType>>,
    /// Custom headers to be passed
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    /// The request's idempotency key
    #[serde(rename = "idempotency_key", skip_serializing_if = "Option::is_none")]
    pub idempotency_key: Option<String>,
    /// Metadata to be passed to the webhook Defaut is {}
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "rate_limit", skip_serializing_if = "Option::is_none")]
    pub rate_limit: Option<i32>,
    /// Url of the webhook
    #[serde(rename = "url")]
    pub url: String,
}

impl CreateWebhookRequest {
    pub fn new(url: String) -> CreateWebhookRequest {
        CreateWebhookRequest {
            description: None,
            disabled: None,
            filter_types: None,
            headers: None,
            idempotency_key: None,
            metadata: None,
            rate_limit: None,
            url,
        }
    }
}

