/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDigitalProductDeliveryRequest {
    /// External URL to digital product
    #[serde(rename = "external_url", skip_serializing_if = "Option::is_none")]
    pub external_url: Option<String>,
    /// Instructions to download and use the digital product
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
}

impl CreateDigitalProductDeliveryRequest {
    pub fn new() -> CreateDigitalProductDeliveryRequest {
        CreateDigitalProductDeliveryRequest {
            external_url: None,
            instructions: None,
        }
    }
}

