/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCreditEntitlementRequest {
    /// Currency for pricing (required if price_per_unit is set)
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
    /// Optional description of the credit entitlement
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Number of days after which credits expire (optional)
    #[serde(rename = "expires_after_days", skip_serializing_if = "Option::is_none")]
    pub expires_after_days: Option<i32>,
    /// Maximum number of times credits can be rolled over
    #[serde(rename = "max_rollover_count", skip_serializing_if = "Option::is_none")]
    pub max_rollover_count: Option<i32>,
    /// Name of the credit entitlement
    #[serde(rename = "name")]
    pub name: String,
    /// Controls how overage is handled at billing cycle end. Defaults to forgive_at_reset if not specified.
    #[serde(rename = "overage_behavior", skip_serializing_if = "Option::is_none")]
    pub overage_behavior: Option<models::CbbOverageBehavior>,
    /// Whether overage charges are enabled when credits run out
    #[serde(rename = "overage_enabled")]
    pub overage_enabled: bool,
    /// Maximum overage units allowed (optional)
    #[serde(rename = "overage_limit", skip_serializing_if = "Option::is_none")]
    pub overage_limit: Option<i64>,
    /// Precision for credit amounts (0-10 decimal places)
    #[serde(rename = "precision")]
    pub precision: i32,
    /// Price per credit unit
    #[serde(rename = "price_per_unit", skip_serializing_if = "Option::is_none")]
    pub price_per_unit: Option<String>,
    /// Whether rollover is enabled for unused credits
    #[serde(rename = "rollover_enabled")]
    pub rollover_enabled: bool,
    /// Percentage of unused credits that can rollover (0-100)
    #[serde(rename = "rollover_percentage", skip_serializing_if = "Option::is_none")]
    pub rollover_percentage: Option<i32>,
    /// Count of timeframe periods for rollover limit
    #[serde(rename = "rollover_timeframe_count", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_count: Option<i32>,
    /// Interval type for rollover timeframe
    #[serde(rename = "rollover_timeframe_interval", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_interval: Option<models::TimeInterval>,
    /// Unit of measurement for the credit (e.g., \"API Calls\", \"Tokens\", \"Credits\")
    #[serde(rename = "unit")]
    pub unit: String,
}

impl CreateCreditEntitlementRequest {
    pub fn new(name: String, overage_enabled: bool, precision: i32, rollover_enabled: bool, unit: String) -> CreateCreditEntitlementRequest {
        CreateCreditEntitlementRequest {
            currency: None,
            description: None,
            expires_after_days: None,
            max_rollover_count: None,
            name,
            overage_behavior: None,
            overage_enabled,
            overage_limit: None,
            precision,
            price_per_unit: None,
            rollover_enabled,
            rollover_percentage: None,
            rollover_timeframe_count: None,
            rollover_timeframe_interval: None,
            unit,
        }
    }
}

