/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreditEntitlementCartResponse : Response struct representing credit entitlement cart details for a subscription
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditEntitlementCartResponse {
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    #[serde(rename = "credit_entitlement_name")]
    pub credit_entitlement_name: String,
    #[serde(rename = "credits_amount")]
    pub credits_amount: String,
    #[serde(rename = "expires_after_days", skip_serializing_if = "Option::is_none")]
    pub expires_after_days: Option<i32>,
    #[serde(rename = "low_balance_threshold_percent", skip_serializing_if = "Option::is_none")]
    pub low_balance_threshold_percent: Option<i32>,
    #[serde(rename = "max_rollover_count", skip_serializing_if = "Option::is_none")]
    pub max_rollover_count: Option<i32>,
    /// Customer's current overage balance for this entitlement
    #[serde(rename = "overage_balance")]
    pub overage_balance: String,
    #[serde(rename = "overage_behavior")]
    pub overage_behavior: models::CbbOverageBehavior,
    #[serde(rename = "overage_enabled")]
    pub overage_enabled: bool,
    #[serde(rename = "overage_limit", skip_serializing_if = "Option::is_none")]
    pub overage_limit: Option<String>,
    #[serde(rename = "product_id")]
    pub product_id: String,
    /// Customer's current remaining credit balance for this entitlement
    #[serde(rename = "remaining_balance")]
    pub remaining_balance: String,
    #[serde(rename = "rollover_enabled")]
    pub rollover_enabled: bool,
    #[serde(rename = "rollover_percentage", skip_serializing_if = "Option::is_none")]
    pub rollover_percentage: Option<i32>,
    #[serde(rename = "rollover_timeframe_count", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_count: Option<i32>,
    #[serde(rename = "rollover_timeframe_interval", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_interval: Option<models::TimeInterval>,
    /// Unit label for the credit entitlement (e.g., \"API Calls\", \"Tokens\")
    #[serde(rename = "unit")]
    pub unit: String,
}

impl CreditEntitlementCartResponse {
    /// Response struct representing credit entitlement cart details for a subscription
    pub fn new(credit_entitlement_id: String, credit_entitlement_name: String, credits_amount: String, overage_balance: String, overage_behavior: models::CbbOverageBehavior, overage_enabled: bool, product_id: String, remaining_balance: String, rollover_enabled: bool, unit: String) -> CreditEntitlementCartResponse {
        CreditEntitlementCartResponse {
            credit_entitlement_id,
            credit_entitlement_name,
            credits_amount,
            expires_after_days: None,
            low_balance_threshold_percent: None,
            max_rollover_count: None,
            overage_balance,
            overage_behavior,
            overage_enabled,
            overage_limit: None,
            product_id,
            remaining_balance,
            rollover_enabled,
            rollover_percentage: None,
            rollover_timeframe_count: None,
            rollover_timeframe_interval: None,
            unit,
        }
    }
}

