/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditBalanceLow {
    #[serde(rename = "available_balance")]
    pub available_balance: String,
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    #[serde(rename = "credit_entitlement_name")]
    pub credit_entitlement_name: String,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "subscription_credits_amount")]
    pub subscription_credits_amount: String,
    #[serde(rename = "subscription_id")]
    pub subscription_id: String,
    #[serde(rename = "threshold_amount")]
    pub threshold_amount: String,
    #[serde(rename = "threshold_percent")]
    pub threshold_percent: i32,
    #[serde(rename = "payload_type")]
    pub payload_type: PayloadType,
}

impl CreditBalanceLow {
    pub fn new(available_balance: String, credit_entitlement_id: String, credit_entitlement_name: String, customer_id: String, subscription_credits_amount: String, subscription_id: String, threshold_amount: String, threshold_percent: i32, payload_type: PayloadType) -> CreditBalanceLow {
        CreditBalanceLow {
            available_balance,
            credit_entitlement_id,
            credit_entitlement_name,
            customer_id,
            subscription_credits_amount,
            subscription_id,
            threshold_amount,
            threshold_percent,
            payload_type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayloadType {
    #[serde(rename = "CreditBalanceLow")]
    CreditBalanceLow,
}

impl Default for PayloadType {
    fn default() -> PayloadType {
        Self::CreditBalanceLow
    }
}

