/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditEntitlementResponse {
    #[serde(rename = "business_id")]
    pub business_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "expires_after_days", skip_serializing_if = "Option::is_none")]
    pub expires_after_days: Option<i32>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "max_rollover_count", skip_serializing_if = "Option::is_none")]
    pub max_rollover_count: Option<i32>,
    #[serde(rename = "name")]
    pub name: String,
    /// Controls how overage is handled at billing cycle end.
    #[serde(rename = "overage_behavior")]
    pub overage_behavior: models::CbbOverageBehavior,
    #[serde(rename = "overage_enabled")]
    pub overage_enabled: bool,
    #[serde(rename = "overage_limit", skip_serializing_if = "Option::is_none")]
    pub overage_limit: Option<i64>,
    #[serde(rename = "precision")]
    pub precision: i32,
    /// Price per credit unit
    #[serde(rename = "price_per_unit", skip_serializing_if = "Option::is_none")]
    pub price_per_unit: Option<String>,
    #[serde(rename = "rollover_enabled")]
    pub rollover_enabled: bool,
    #[serde(rename = "rollover_percentage", skip_serializing_if = "Option::is_none")]
    pub rollover_percentage: Option<i32>,
    #[serde(rename = "rollover_timeframe_count", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_count: Option<i32>,
    #[serde(rename = "rollover_timeframe_interval", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_interval: Option<models::TimeInterval>,
    #[serde(rename = "unit")]
    pub unit: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl CreditEntitlementResponse {
    pub fn new(business_id: String, created_at: String, id: String, name: String, overage_behavior: models::CbbOverageBehavior, overage_enabled: bool, precision: i32, rollover_enabled: bool, unit: String, updated_at: String) -> CreditEntitlementResponse {
        CreditEntitlementResponse {
            business_id,
            created_at,
            currency: None,
            description: None,
            expires_after_days: None,
            id,
            max_rollover_count: None,
            name,
            overage_behavior,
            overage_enabled,
            overage_limit: None,
            precision,
            price_per_unit: None,
            rollover_enabled,
            rollover_percentage: None,
            rollover_timeframe_count: None,
            rollover_timeframe_interval: None,
            unit,
            updated_at,
        }
    }
}

