/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreditEntitlementUsageStatus : Per-entitlement credit usage status for a subscription
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditEntitlementUsageStatus {
    /// Customer's current credit balance for this entitlement (customer-wide)
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    #[serde(rename = "credit_entitlement_name")]
    pub credit_entitlement_name: String,
    /// True if overage has reached or exceeded the limit. When true, further deductions that would increase overage will fail.
    #[serde(rename = "limit_reached")]
    pub limit_reached: bool,
    /// Current overage amount accrued (customer-wide)
    #[serde(rename = "overage")]
    pub overage: String,
    /// Whether overage is enabled for this entitlement on this subscription
    #[serde(rename = "overage_enabled")]
    pub overage_enabled: bool,
    /// Maximum allowed overage before deductions are blocked. None means unlimited overage (when overage_enabled is true).
    #[serde(rename = "overage_limit", skip_serializing_if = "Option::is_none")]
    pub overage_limit: Option<String>,
    /// How much more overage can accumulate before being blocked. None if overage is not enabled or there is no limit (unlimited). A value of 0 means the next deduction that increases overage will be blocked.
    #[serde(rename = "remaining_headroom", skip_serializing_if = "Option::is_none")]
    pub remaining_headroom: Option<String>,
    /// Unit label for the credit entitlement (e.g. \"API Calls\", \"Tokens\")
    #[serde(rename = "unit")]
    pub unit: String,
}

impl CreditEntitlementUsageStatus {
    /// Per-entitlement credit usage status for a subscription
    pub fn new(balance: String, credit_entitlement_id: String, credit_entitlement_name: String, limit_reached: bool, overage: String, overage_enabled: bool, unit: String) -> CreditEntitlementUsageStatus {
        CreditEntitlementUsageStatus {
            balance,
            credit_entitlement_id,
            credit_entitlement_name,
            limit_reached,
            overage,
            overage_enabled,
            overage_limit: None,
            remaining_headroom: None,
            unit,
        }
    }
}

