/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerCreditEntitlementItem : A credit entitlement with the customer's current balance
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerCreditEntitlementItem {
    /// Customer's current remaining credit balance
    #[serde(rename = "balance")]
    pub balance: String,
    /// Credit entitlement ID
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    /// Description of the credit entitlement
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name of the credit entitlement
    #[serde(rename = "name")]
    pub name: String,
    /// Customer's current overage balance
    #[serde(rename = "overage")]
    pub overage: String,
    /// Unit label (e.g. \"API Calls\", \"Tokens\")
    #[serde(rename = "unit")]
    pub unit: String,
}

impl CustomerCreditEntitlementItem {
    /// A credit entitlement with the customer's current balance
    pub fn new(balance: String, credit_entitlement_id: String, name: String, overage: String, unit: String) -> CustomerCreditEntitlementItem {
        CustomerCreditEntitlementItem {
            balance,
            credit_entitlement_id,
            description: None,
            name,
            overage,
            unit,
        }
    }
}

