/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomerLedgerEventType {
    #[serde(rename = "payment")]
    Payment,
    #[serde(rename = "payment_reversal")]
    PaymentReversal,
    #[serde(rename = "refund")]
    Refund,
    #[serde(rename = "refund_reversal")]
    RefundReversal,
    #[serde(rename = "dispute")]
    Dispute,
    #[serde(rename = "dispute_reversal")]
    DisputeReversal,
    #[serde(rename = "merchant_adjustment")]
    MerchantAdjustment,

}

impl std::fmt::Display for CustomerLedgerEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Payment => write!(f, "payment"),
            Self::PaymentReversal => write!(f, "payment_reversal"),
            Self::Refund => write!(f, "refund"),
            Self::RefundReversal => write!(f, "refund_reversal"),
            Self::Dispute => write!(f, "dispute"),
            Self::DisputeReversal => write!(f, "dispute_reversal"),
            Self::MerchantAdjustment => write!(f, "merchant_adjustment"),
        }
    }
}

impl Default for CustomerLedgerEventType {
    fn default() -> CustomerLedgerEventType {
        Self::Payment
    }
}

