/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerResponse {
    #[serde(rename = "business_id")]
    pub business_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "email")]
    pub email: String,
    /// Additional metadata for the customer
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl CustomerResponse {
    pub fn new(business_id: String, created_at: String, customer_id: String, email: String, name: String) -> CustomerResponse {
        CustomerResponse {
            business_id,
            created_at,
            customer_id,
            email,
            metadata: None,
            name,
            phone_number: None,
        }
    }
}

