/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPaymentMethodItem {
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Box<models::CustomerPaymentMethodCardSummary>>,
    #[serde(rename = "last_used_at", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<String>,
    #[serde(rename = "payment_method")]
    pub payment_method: models::PaymentMethod,
    #[serde(rename = "payment_method_id")]
    pub payment_method_id: String,
    #[serde(rename = "payment_method_type", skip_serializing_if = "Option::is_none")]
    pub payment_method_type: Option<models::PaymentMethodTypes>,
    #[serde(rename = "recurring_enabled", skip_serializing_if = "Option::is_none")]
    pub recurring_enabled: Option<bool>,
}

impl CustomerPaymentMethodItem {
    pub fn new(payment_method: models::PaymentMethod, payment_method_id: String) -> CustomerPaymentMethodItem {
        CustomerPaymentMethodItem {
            card: None,
            last_used_at: None,
            payment_method,
            payment_method_id,
            payment_method_type: None,
            recurring_enabled: None,
        }
    }
}

