/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomerRequest {
    AttachExistingCustomer(Box<models::AttachExistingCustomer>),
    NewCustomer(Box<models::NewCustomer>),
}

impl Default for CustomerRequest {
    fn default() -> Self {
        Self::AttachExistingCustomer(Default::default())
    }
}

