/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFieldType : Custom field type for checkout forms
/// Custom field type for checkout forms
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CustomFieldType {
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "number")]
    Number,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "url")]
    Url,
    #[serde(rename = "date")]
    Date,
    #[serde(rename = "dropdown")]
    Dropdown,
    #[serde(rename = "boolean")]
    Boolean,

}

impl std::fmt::Display for CustomFieldType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Text => write!(f, "text"),
            Self::Number => write!(f, "number"),
            Self::Email => write!(f, "email"),
            Self::Url => write!(f, "url"),
            Self::Date => write!(f, "date"),
            Self::Dropdown => write!(f, "dropdown"),
            Self::Boolean => write!(f, "boolean"),
        }
    }
}

impl Default for CustomFieldType {
    fn default() -> CustomFieldType {
        Self::Text
    }
}

