/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerWalletsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::CustomerWalletResponse>,
    /// Sum of all wallet balances converted to USD (in smallest unit)
    #[serde(rename = "total_balance_usd")]
    pub total_balance_usd: i64,
}

impl CustomerWalletsResponse {
    pub fn new(items: Vec<models::CustomerWalletResponse>, total_balance_usd: i64) -> CustomerWalletsResponse {
        CustomerWalletsResponse {
            items,
            total_balance_usd,
        }
    }
}

