/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomFieldResponse : Customer's response to a custom field
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFieldResponse {
    /// Key matching the custom field definition
    #[serde(rename = "key")]
    pub key: String,
    /// Value provided by customer
    #[serde(rename = "value")]
    pub value: String,
}

impl CustomFieldResponse {
    /// Customer's response to a custom field
    pub fn new(key: String, value: String) -> CustomFieldResponse {
        CustomFieldResponse {
            key,
            value,
        }
    }
}

