/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomerCreditBalanceResponse : Response for a customer's credit balance
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerCreditBalanceResponse {
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "last_transaction_at", skip_serializing_if = "Option::is_none")]
    pub last_transaction_at: Option<String>,
    #[serde(rename = "overage")]
    pub overage: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl CustomerCreditBalanceResponse {
    /// Response for a customer's credit balance
    pub fn new(balance: String, created_at: String, credit_entitlement_id: String, customer_id: String, id: String, overage: String, updated_at: String) -> CustomerCreditBalanceResponse {
        CustomerCreditBalanceResponse {
            balance,
            created_at,
            credit_entitlement_id,
            customer_id,
            id,
            last_transaction_at: None,
            overage,
            updated_at,
        }
    }
}

