/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerWalletResponse {
    #[serde(rename = "balance")]
    pub balance: i64,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl CustomerWalletResponse {
    pub fn new(balance: i64, created_at: String, currency: models::Currency, customer_id: String, updated_at: String) -> CustomerWalletResponse {
        CustomerWalletResponse {
            balance,
            created_at,
            currency,
            customer_id,
            updated_at,
        }
    }
}

