/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerLimitedDetailsResponse {
    /// Unique identifier for the customer
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    /// Email address of the customer
    #[serde(rename = "email")]
    pub email: String,
    /// Additional metadata associated with the customer
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    /// Full name of the customer
    #[serde(rename = "name")]
    pub name: String,
    /// Phone number of the customer
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl CustomerLimitedDetailsResponse {
    pub fn new(customer_id: String, email: String, name: String) -> CustomerLimitedDetailsResponse {
        CustomerLimitedDetailsResponse {
            customer_id,
            email,
            metadata: None,
            name,
            phone_number: None,
        }
    }
}

