/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerBalanceConfig {
    /// Allows Customer Credit to be purchased to settle payments
    #[serde(rename = "allow_customer_credits_purchase", skip_serializing_if = "Option::is_none")]
    pub allow_customer_credits_purchase: Option<bool>,
    /// Allows Customer Credit Balance to be used to settle payments
    #[serde(rename = "allow_customer_credits_usage", skip_serializing_if = "Option::is_none")]
    pub allow_customer_credits_usage: Option<bool>,
}

impl CustomerBalanceConfig {
    pub fn new() -> CustomerBalanceConfig {
        CustomerBalanceConfig {
            allow_customer_credits_purchase: None,
            allow_customer_credits_usage: None,
        }
    }
}

