/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomerPaymentMethodCardSummary {
    #[serde(rename = "card_holder_name", skip_serializing_if = "Option::is_none")]
    pub card_holder_name: Option<String>,
    #[serde(rename = "card_issuing_country", skip_serializing_if = "Option::is_none")]
    pub card_issuing_country: Option<models::CountryCodeAlpha2>,
    #[serde(rename = "card_network", skip_serializing_if = "Option::is_none")]
    pub card_network: Option<String>,
    #[serde(rename = "card_type", skip_serializing_if = "Option::is_none")]
    pub card_type: Option<String>,
    #[serde(rename = "expiry_month", skip_serializing_if = "Option::is_none")]
    pub expiry_month: Option<String>,
    #[serde(rename = "expiry_year", skip_serializing_if = "Option::is_none")]
    pub expiry_year: Option<String>,
    #[serde(rename = "last4_digits", skip_serializing_if = "Option::is_none")]
    pub last4_digits: Option<String>,
}

impl CustomerPaymentMethodCardSummary {
    pub fn new() -> CustomerPaymentMethodCardSummary {
        CustomerPaymentMethodCardSummary {
            card_holder_name: None,
            card_issuing_country: None,
            card_network: None,
            card_type: None,
            expiry_month: None,
            expiry_year: None,
            last4_digits: None,
        }
    }
}

