/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DigitalFilesConfig1 {
    /// Populated digital-files payload with each file's metadata and a short-lived presigned download URL.
    #[serde(rename = "digital_files")]
    pub digital_files: Box<models::ResolvedDigitalFiles>,
}

impl DigitalFilesConfig1 {
    pub fn new(digital_files: models::ResolvedDigitalFiles) -> DigitalFilesConfig1 {
        DigitalFilesConfig1 {
            digital_files: Box::new(digital_files),
        }
    }
}

