/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DigitalProductDeliveryFile {
    #[serde(rename = "file_id")]
    pub file_id: uuid::Uuid,
    #[serde(rename = "file_name")]
    pub file_name: String,
    #[serde(rename = "url")]
    pub url: String,
}

impl DigitalProductDeliveryFile {
    pub fn new(file_id: uuid::Uuid, file_name: String, url: String) -> DigitalProductDeliveryFile {
        DigitalProductDeliveryFile {
            file_id,
            file_name,
            url,
        }
    }
}

