/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscordConfig {
    /// Discord guild (server) ID.
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    /// Optional Discord role to assign within the guild.
    #[serde(rename = "role_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<Option<String>>,
}

impl DiscordConfig {
    pub fn new(guild_id: String) -> DiscordConfig {
        DiscordConfig {
            guild_id,
            role_id: None,
        }
    }
}

