/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisputeCancelledPostRequest {
    /// The business identifier
    #[serde(rename = "business_id")]
    pub business_id: String,
    #[serde(rename = "data")]
    pub data: Box<models::DisputeResponse>,
    /// The timestamp of when the event occurred
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// The event type
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl DisputeCancelledPostRequest {
    pub fn new(business_id: String, data: models::DisputeResponse, timestamp: String, r#type: Type) -> DisputeCancelledPostRequest {
        DisputeCancelledPostRequest {
            business_id,
            data: Box::new(data),
            timestamp,
            r#type,
        }
    }
}
/// The event type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "dispute.cancelled")]
    DisputeCancelled,
}

impl Default for Type {
    fn default() -> Type {
        Self::DisputeCancelled
    }
}

