/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DisputeStatus {
    #[serde(rename = "dispute_opened")]
    DisputeOpened,
    #[serde(rename = "dispute_expired")]
    DisputeExpired,
    #[serde(rename = "dispute_accepted")]
    DisputeAccepted,
    #[serde(rename = "dispute_cancelled")]
    DisputeCancelled,
    #[serde(rename = "dispute_challenged")]
    DisputeChallenged,
    #[serde(rename = "dispute_won")]
    DisputeWon,
    #[serde(rename = "dispute_lost")]
    DisputeLost,

}

impl std::fmt::Display for DisputeStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DisputeOpened => write!(f, "dispute_opened"),
            Self::DisputeExpired => write!(f, "dispute_expired"),
            Self::DisputeAccepted => write!(f, "dispute_accepted"),
            Self::DisputeCancelled => write!(f, "dispute_cancelled"),
            Self::DisputeChallenged => write!(f, "dispute_challenged"),
            Self::DisputeWon => write!(f, "dispute_won"),
            Self::DisputeLost => write!(f, "dispute_lost"),
        }
    }
}

impl Default for DisputeStatus {
    fn default() -> DisputeStatus {
        Self::DisputeOpened
    }
}

