/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DisputeStage {
    #[serde(rename = "pre_dispute")]
    PreDispute,
    #[serde(rename = "dispute")]
    Dispute,
    #[serde(rename = "pre_arbitration")]
    PreArbitration,

}

impl std::fmt::Display for DisputeStage {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PreDispute => write!(f, "pre_dispute"),
            Self::Dispute => write!(f, "dispute"),
            Self::PreArbitration => write!(f, "pre_arbitration"),
        }
    }
}

impl Default for DisputeStage {
    fn default() -> DisputeStage {
        Self::PreDispute
    }
}

