/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EntitlementIntegrationType {
    #[serde(rename = "discord")]
    Discord,
    #[serde(rename = "telegram")]
    Telegram,
    #[serde(rename = "github")]
    Github,
    #[serde(rename = "figma")]
    Figma,
    #[serde(rename = "framer")]
    Framer,
    #[serde(rename = "notion")]
    Notion,
    #[serde(rename = "digital_files")]
    DigitalFiles,
    #[serde(rename = "license_key")]
    LicenseKey,

}

impl std::fmt::Display for EntitlementIntegrationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Discord => write!(f, "discord"),
            Self::Telegram => write!(f, "telegram"),
            Self::Github => write!(f, "github"),
            Self::Figma => write!(f, "figma"),
            Self::Framer => write!(f, "framer"),
            Self::Notion => write!(f, "notion"),
            Self::DigitalFiles => write!(f, "digital_files"),
            Self::LicenseKey => write!(f, "license_key"),
        }
    }
}

impl Default for EntitlementIntegrationType {
    fn default() -> EntitlementIntegrationType {
        Self::Discord
    }
}

