/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EntitlementGrantStatus {
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Delivered")]
    Delivered,
    #[serde(rename = "Failed")]
    Failed,
    #[serde(rename = "Revoked")]
    Revoked,

}

impl std::fmt::Display for EntitlementGrantStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "Pending"),
            Self::Delivered => write!(f, "Delivered"),
            Self::Failed => write!(f, "Failed"),
            Self::Revoked => write!(f, "Revoked"),
        }
    }
}

impl Default for EntitlementGrantStatus {
    fn default() -> EntitlementGrantStatus {
        Self::Pending
    }
}

