/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Event {
    #[serde(rename = "business_id")]
    pub business_id: String,
    #[serde(rename = "customer_id")]
    pub customer_id: String,
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "event_name")]
    pub event_name: String,
    /// Arbitrary key-value metadata. Values can be string, integer, number, or boolean.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, models::EventMetadataValue>>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl Event {
    pub fn new(business_id: String, customer_id: String, event_id: String, event_name: String, timestamp: String) -> Event {
        Event {
            business_id,
            customer_id,
            event_id,
            event_name,
            metadata: None,
            timestamp,
        }
    }
}

