/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventType : Event types for Dodo events
/// Event types for Dodo events
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "payment.succeeded")]
    PaymentSucceeded,
    #[serde(rename = "payment.failed")]
    PaymentFailed,
    #[serde(rename = "payment.processing")]
    PaymentProcessing,
    #[serde(rename = "payment.cancelled")]
    PaymentCancelled,
    #[serde(rename = "refund.succeeded")]
    RefundSucceeded,
    #[serde(rename = "refund.failed")]
    RefundFailed,
    #[serde(rename = "dispute.opened")]
    DisputeOpened,
    #[serde(rename = "dispute.expired")]
    DisputeExpired,
    #[serde(rename = "dispute.accepted")]
    DisputeAccepted,
    #[serde(rename = "dispute.cancelled")]
    DisputeCancelled,
    #[serde(rename = "dispute.challenged")]
    DisputeChallenged,
    #[serde(rename = "dispute.won")]
    DisputeWon,
    #[serde(rename = "dispute.lost")]
    DisputeLost,
    #[serde(rename = "subscription.active")]
    SubscriptionActive,
    #[serde(rename = "subscription.renewed")]
    SubscriptionRenewed,
    #[serde(rename = "subscription.on_hold")]
    SubscriptionOnHold,
    #[serde(rename = "subscription.cancelled")]
    SubscriptionCancelled,
    #[serde(rename = "subscription.failed")]
    SubscriptionFailed,
    #[serde(rename = "subscription.expired")]
    SubscriptionExpired,
    #[serde(rename = "subscription.plan_changed")]
    SubscriptionPlanChanged,
    #[serde(rename = "subscription.updated")]
    SubscriptionUpdated,
    #[serde(rename = "license_key.created")]
    LicenseKeyCreated,
    #[serde(rename = "payout.not_initiated")]
    PayoutNotInitiated,
    #[serde(rename = "payout.on_hold")]
    PayoutOnHold,
    #[serde(rename = "payout.in_progress")]
    PayoutInProgress,
    #[serde(rename = "payout.failed")]
    PayoutFailed,
    #[serde(rename = "payout.success")]
    PayoutSuccess,
    #[serde(rename = "credit.added")]
    CreditAdded,
    #[serde(rename = "credit.deducted")]
    CreditDeducted,
    #[serde(rename = "credit.expired")]
    CreditExpired,
    #[serde(rename = "credit.rolled_over")]
    CreditRolledOver,
    #[serde(rename = "credit.rollover_forfeited")]
    CreditRolloverForfeited,
    #[serde(rename = "credit.overage_charged")]
    CreditOverageCharged,
    #[serde(rename = "credit.manual_adjustment")]
    CreditManualAdjustment,
    #[serde(rename = "credit.balance_low")]
    CreditBalanceLow,

}

impl std::fmt::Display for EventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PaymentSucceeded => write!(f, "payment.succeeded"),
            Self::PaymentFailed => write!(f, "payment.failed"),
            Self::PaymentProcessing => write!(f, "payment.processing"),
            Self::PaymentCancelled => write!(f, "payment.cancelled"),
            Self::RefundSucceeded => write!(f, "refund.succeeded"),
            Self::RefundFailed => write!(f, "refund.failed"),
            Self::DisputeOpened => write!(f, "dispute.opened"),
            Self::DisputeExpired => write!(f, "dispute.expired"),
            Self::DisputeAccepted => write!(f, "dispute.accepted"),
            Self::DisputeCancelled => write!(f, "dispute.cancelled"),
            Self::DisputeChallenged => write!(f, "dispute.challenged"),
            Self::DisputeWon => write!(f, "dispute.won"),
            Self::DisputeLost => write!(f, "dispute.lost"),
            Self::SubscriptionActive => write!(f, "subscription.active"),
            Self::SubscriptionRenewed => write!(f, "subscription.renewed"),
            Self::SubscriptionOnHold => write!(f, "subscription.on_hold"),
            Self::SubscriptionCancelled => write!(f, "subscription.cancelled"),
            Self::SubscriptionFailed => write!(f, "subscription.failed"),
            Self::SubscriptionExpired => write!(f, "subscription.expired"),
            Self::SubscriptionPlanChanged => write!(f, "subscription.plan_changed"),
            Self::SubscriptionUpdated => write!(f, "subscription.updated"),
            Self::LicenseKeyCreated => write!(f, "license_key.created"),
            Self::PayoutNotInitiated => write!(f, "payout.not_initiated"),
            Self::PayoutOnHold => write!(f, "payout.on_hold"),
            Self::PayoutInProgress => write!(f, "payout.in_progress"),
            Self::PayoutFailed => write!(f, "payout.failed"),
            Self::PayoutSuccess => write!(f, "payout.success"),
            Self::CreditAdded => write!(f, "credit.added"),
            Self::CreditDeducted => write!(f, "credit.deducted"),
            Self::CreditExpired => write!(f, "credit.expired"),
            Self::CreditRolledOver => write!(f, "credit.rolled_over"),
            Self::CreditRolloverForfeited => write!(f, "credit.rollover_forfeited"),
            Self::CreditOverageCharged => write!(f, "credit.overage_charged"),
            Self::CreditManualAdjustment => write!(f, "credit.manual_adjustment"),
            Self::CreditBalanceLow => write!(f, "credit.balance_low"),
        }
    }
}

impl Default for EventType {
    fn default() -> EventType {
        Self::PaymentSucceeded
    }
}

