/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventMetadataValue : Metadata value can be a string, integer, number, or boolean
/// Metadata value can be a string, integer, number, or boolean
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EventMetadataValue {
    String(String),
    Integer(i64),
    Number(f64),
    Boolean(bool),
}

impl Default for EventMetadataValue {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

