/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Existing {
    #[serde(rename = "payment_method_id")]
    pub payment_method_id: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl Existing {
    pub fn new(payment_method_id: String, r#type: Type) -> Existing {
        Existing {
            payment_method_id,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "existing")]
    Existing,
}

impl Default for Type {
    fn default() -> Type {
        Self::Existing
    }
}

