/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FailedEvent {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "event_id")]
    pub event_id: String,
}

impl FailedEvent {
    pub fn new(error: String, event_id: String) -> FailedEvent {
        FailedEvent {
            error,
            event_id,
        }
    }
}

