/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FigmaConfig {
    /// Figma file identifier to grant access to.
    #[serde(rename = "figma_file_id")]
    pub figma_file_id: String,
}

impl FigmaConfig {
    pub fn new(figma_file_id: String) -> FigmaConfig {
        FigmaConfig {
            figma_file_id,
        }
    }
}

