/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterType : Filter type - supports up to 3 levels of nesting (Level 1: conditions or Level 2 filters)
/// Filter type - supports up to 3 levels of nesting (Level 1: conditions or Level 2 filters)
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FilterType {
    /// Direct filter conditions - array of condition objects with key, operator, and value
    DirectFilterConditions(Vec<models::MeterFilterCondition>),
    /// Nested filters - supports up to 3 levels deep
    NestedMeterFilters(Vec<models::MeterFilter1>),
}

impl Default for FilterType {
    fn default() -> Self {
        Self::DirectFilterConditions(Default::default())
    }
}
