/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilterOperator {
    #[serde(rename = "equals")]
    Equals,
    #[serde(rename = "not_equals")]
    NotEquals,
    #[serde(rename = "greater_than")]
    GreaterThan,
    #[serde(rename = "greater_than_or_equals")]
    GreaterThanOrEquals,
    #[serde(rename = "less_than")]
    LessThan,
    #[serde(rename = "less_than_or_equals")]
    LessThanOrEquals,
    #[serde(rename = "contains")]
    Contains,
    #[serde(rename = "does_not_contain")]
    DoesNotContain,

}

impl std::fmt::Display for FilterOperator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Equals => write!(f, "equals"),
            Self::NotEquals => write!(f, "not_equals"),
            Self::GreaterThan => write!(f, "greater_than"),
            Self::GreaterThanOrEquals => write!(f, "greater_than_or_equals"),
            Self::LessThan => write!(f, "less_than"),
            Self::LessThanOrEquals => write!(f, "less_than_or_equals"),
            Self::Contains => write!(f, "contains"),
            Self::DoesNotContain => write!(f, "does_not_contain"),
        }
    }
}

impl Default for FilterOperator {
    fn default() -> FilterOperator {
        Self::Equals
    }
}

