/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FontWeight : Font weight options for checkout UI
/// Font weight options for checkout UI
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FontWeight {
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "bold")]
    Bold,
    #[serde(rename = "extraBold")]
    ExtraBold,

}

impl std::fmt::Display for FontWeight {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Normal => write!(f, "normal"),
            Self::Medium => write!(f, "medium"),
            Self::Bold => write!(f, "bold"),
            Self::ExtraBold => write!(f, "extraBold"),
        }
    }
}

impl Default for FontWeight {
    fn default() -> FontWeight {
        Self::Normal
    }
}

