/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FramerConfig {
    /// Framer template identifier to grant access to.
    #[serde(rename = "framer_template_id")]
    pub framer_template_id: String,
}

impl FramerConfig {
    pub fn new(framer_template_id: String) -> FramerConfig {
        FramerConfig {
            framer_template_id,
        }
    }
}

