/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventsQuery {
    /// Filter events by customer ID
    #[serde(rename = "customer_id", skip_serializing_if = "Option::is_none")]
    pub customer_id: Option<String>,
    /// Filter events created before this timestamp
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    /// Filter events by event name. If both event_name and meter_id are provided, they must match the meter's configured event_name
    #[serde(rename = "event_name", skip_serializing_if = "Option::is_none")]
    pub event_name: Option<String>,
    /// Filter events by meter ID. When provided, only events that match the meter's event_name and filter criteria will be returned
    #[serde(rename = "meter_id", skip_serializing_if = "Option::is_none")]
    pub meter_id: Option<String>,
    /// Page number (0-based, default: 0)
    #[serde(rename = "page_number", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    /// Number of events to return per page (default: 10)
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    /// Filter events created after this timestamp
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
}

impl GetEventsQuery {
    pub fn new() -> GetEventsQuery {
        GetEventsQuery {
            customer_id: None,
            end: None,
            event_name: None,
            meter_id: None,
            page_number: None,
            page_size: None,
            start: None,
        }
    }
}

