/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWebhookSecretResponse {
    #[serde(rename = "secret")]
    pub secret: String,
}

impl GetWebhookSecretResponse {
    pub fn new(secret: String) -> GetWebhookSecretResponse {
        GetWebhookSecretResponse {
            secret,
        }
    }
}

