/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::Event>,
}

impl GetEventsResponse {
    pub fn new(items: Vec<models::Event>) -> GetEventsResponse {
        GetEventsResponse {
            items,
        }
    }
}

