/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetWebhookHeadersResponse : The value of the headers is returned in the `headers` field.  Sensitive headers that have been redacted are returned in the sensitive field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWebhookHeadersResponse {
    /// List of headers configured
    #[serde(rename = "headers")]
    pub headers: std::collections::HashMap<String, String>,
    /// Sensitive headers without the value
    #[serde(rename = "sensitive")]
    pub sensitive: Vec<String>,
}

impl GetWebhookHeadersResponse {
    /// The value of the headers is returned in the `headers` field.  Sensitive headers that have been redacted are returned in the sensitive field.
    pub fn new(headers: std::collections::HashMap<String, String>, sensitive: Vec<String>) -> GetWebhookHeadersResponse {
        GetWebhookHeadersResponse {
            headers,
            sensitive,
        }
    }
}

