/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetProductsListResponseItem {
    /// Unique identifier for the business to which the product belongs.
    #[serde(rename = "business_id")]
    pub business_id: String,
    /// Timestamp when the product was created.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Currency of the price
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
    /// Description of the product, optional.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URL of the product image, optional.
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Indicates if the product is recurring (e.g., subscriptions).
    #[serde(rename = "is_recurring")]
    pub is_recurring: bool,
    /// Additional custom data associated with the product
    #[serde(rename = "metadata")]
    pub metadata: std::collections::HashMap<String, String>,
    /// Name of the product, optional.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Price of the product, optional.  The price is represented in the lowest denomination of the currency. For example: - In USD, a price of `$12.34` would be represented as `1234` (cents). - In JPY, a price of `¥1500` would be represented as `1500` (yen). - In INR, a price of `₹1234.56` would be represented as `123456` (paise).  This ensures precision and avoids floating-point rounding errors.
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    /// Details of the price
    #[serde(rename = "price_detail", skip_serializing_if = "Option::is_none")]
    pub price_detail: Option<Box<models::Price>>,
    /// Unique identifier for the product.
    #[serde(rename = "product_id")]
    pub product_id: String,
    /// Tax category associated with the product.
    #[serde(rename = "tax_category")]
    pub tax_category: models::TaxCategory,
    /// Indicates if the price is tax inclusive
    #[serde(rename = "tax_inclusive", skip_serializing_if = "Option::is_none")]
    pub tax_inclusive: Option<bool>,
    /// Timestamp when the product was last updated.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl GetProductsListResponseItem {
    pub fn new(business_id: String, created_at: String, is_recurring: bool, metadata: std::collections::HashMap<String, String>, product_id: String, tax_category: models::TaxCategory, updated_at: String) -> GetProductsListResponseItem {
        GetProductsListResponseItem {
            business_id,
            created_at,
            currency: None,
            description: None,
            image: None,
            is_recurring,
            metadata,
            name: None,
            price: None,
            price_detail: None,
            product_id,
            tax_category,
            tax_inclusive: None,
            updated_at,
        }
    }
}

