/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubConfig {
    /// Permission to grant on the repository.
    #[serde(rename = "permission")]
    pub permission: models::GithubPermission,
    /// Repository or organisation slug to grant access to.
    #[serde(rename = "target_id")]
    pub target_id: String,
}

impl GithubConfig {
    pub fn new(permission: models::GithubPermission, target_id: String) -> GithubConfig {
        GithubConfig {
            permission,
            target_id,
        }
    }
}

