/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupProduct {
    /// Product ID to include in the group
    #[serde(rename = "product_id")]
    pub product_id: String,
    /// Status of the product in this group (defaults to true if not provided)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<bool>,
}

impl GroupProduct {
    pub fn new(product_id: String) -> GroupProduct {
        GroupProduct {
            product_id,
            status: None,
        }
    }
}

