/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImmediateCharge {
    #[serde(rename = "line_items")]
    pub line_items: Vec<models::LineItem>,
    #[serde(rename = "summary")]
    pub summary: Box<models::LineItemSummary>,
}

impl ImmediateCharge {
    pub fn new(line_items: Vec<models::LineItem>, summary: models::LineItemSummary) -> ImmediateCharge {
        ImmediateCharge {
            line_items,
            summary: Box::new(summary),
        }
    }
}

