/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IngestEventsResponse {
    #[serde(rename = "ingested_count")]
    pub ingested_count: i32,
}

impl IngestEventsResponse {
    pub fn new(ingested_count: i32) -> IngestEventsResponse {
        IngestEventsResponse {
            ingested_count,
        }
    }
}

