/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntegrationConfig : Integration-specific configuration supplied when creating or updating an entitlement. The shape required matches the entitlement's `integration_type`.
/// Integration-specific configuration supplied when creating or updating an entitlement. The shape required matches the entitlement's `integration_type`.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IntegrationConfig {
    GithubConfig(Box<models::GithubConfig>),
    DiscordConfig(Box<models::DiscordConfig>),
    TelegramConfig(Box<models::TelegramConfig>),
    FigmaConfig(Box<models::FigmaConfig>),
    FramerConfig(Box<models::FramerConfig>),
    NotionConfig(Box<models::NotionConfig>),
    DigitalFilesConfig(Box<models::DigitalFilesConfig>),
    LicenseKeyConfig(Box<models::LicenseKeyConfig>),
}

impl Default for IntegrationConfig {
    fn default() -> Self {
        Self::GithubConfig(Default::default())
    }
}

