/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IntegrationConfigResponse : Integration-specific configuration on an entitlement read response.  For `digital_files` entitlements the response includes presigned download URLs for each attached file; other integrations match the shape supplied at creation.
/// Integration-specific configuration on an entitlement read response.  For `digital_files` entitlements the response includes presigned download URLs for each attached file; other integrations match the shape supplied at creation.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IntegrationConfigResponse {
    GithubConfig(Box<models::GithubConfig>),
    DiscordConfig(Box<models::DiscordConfig>),
    TelegramConfig(Box<models::TelegramConfig>),
    FigmaConfig(Box<models::FigmaConfig>),
    FramerConfig(Box<models::FramerConfig>),
    NotionConfig(Box<models::NotionConfig>),
    DigitalFilesConfig1(Box<models::DigitalFilesConfig1>),
    LicenseKeyConfig(Box<models::LicenseKeyConfig>),
}

impl Default for IntegrationConfigResponse {
    fn default() -> Self {
        Self::GithubConfig(Default::default())
    }
}

