/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LedgerEventType {
    #[serde(rename = "payment")]
    Payment,
    #[serde(rename = "refund")]
    Refund,
    #[serde(rename = "refund_reversal")]
    RefundReversal,
    #[serde(rename = "dispute")]
    Dispute,
    #[serde(rename = "dispute_reversal")]
    DisputeReversal,
    #[serde(rename = "tax")]
    Tax,
    #[serde(rename = "tax_reversal")]
    TaxReversal,
    #[serde(rename = "payment_fees")]
    PaymentFees,
    #[serde(rename = "refund_fees")]
    RefundFees,
    #[serde(rename = "refund_fees_reversal")]
    RefundFeesReversal,
    #[serde(rename = "dispute_fees")]
    DisputeFees,
    #[serde(rename = "payout")]
    Payout,
    #[serde(rename = "payout_fees")]
    PayoutFees,
    #[serde(rename = "payout_reversal")]
    PayoutReversal,
    #[serde(rename = "payout_fees_reversal")]
    PayoutFeesReversal,
    #[serde(rename = "dodo_credits")]
    DodoCredits,
    #[serde(rename = "adjustment")]
    Adjustment,
    #[serde(rename = "currency_conversion")]
    CurrencyConversion,

}

impl std::fmt::Display for LedgerEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Payment => write!(f, "payment"),
            Self::Refund => write!(f, "refund"),
            Self::RefundReversal => write!(f, "refund_reversal"),
            Self::Dispute => write!(f, "dispute"),
            Self::DisputeReversal => write!(f, "dispute_reversal"),
            Self::Tax => write!(f, "tax"),
            Self::TaxReversal => write!(f, "tax_reversal"),
            Self::PaymentFees => write!(f, "payment_fees"),
            Self::RefundFees => write!(f, "refund_fees"),
            Self::RefundFeesReversal => write!(f, "refund_fees_reversal"),
            Self::DisputeFees => write!(f, "dispute_fees"),
            Self::Payout => write!(f, "payout"),
            Self::PayoutFees => write!(f, "payout_fees"),
            Self::PayoutReversal => write!(f, "payout_reversal"),
            Self::PayoutFeesReversal => write!(f, "payout_fees_reversal"),
            Self::DodoCredits => write!(f, "dodo_credits"),
            Self::Adjustment => write!(f, "adjustment"),
            Self::CurrencyConversion => write!(f, "currency_conversion"),
        }
    }
}

impl Default for LedgerEventType {
    fn default() -> LedgerEventType {
        Self::Payment
    }
}

