/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Level1Clause : Level 1: Can be conditions or nested filters (2 more levels allowed)
/// Level 1: Can be conditions or nested filters (2 more levels allowed)
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Level1Clause {
    /// Array of filter conditions
    Level1FilterConditions(Vec<models::MeterFilterCondition>),
    /// Array of level 2 nested filters
    Level1NestedFilters(Vec<models::MeterFilter1>),
}

impl Default for Level1Clause {
    fn default() -> Self {
        Self::Level1FilterConditions(Default::default())
    }
}
