/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Level2Clause : Level 2: Can be conditions or nested filters (1 more level allowed)
/// Level 2: Can be conditions or nested filters (1 more level allowed)
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Level2Clause {
    /// Array of filter conditions
    Level2FilterConditions(Vec<models::MeterFilterCondition>),
    /// Array of level 3 nested filters (final level)
    Level2NestedFilters(Vec<models::MeterFilter1>),
}

impl Default for Level2Clause {
    fn default() -> Self {
        Self::Level2FilterConditions(Default::default())
    }
}
