/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseKeyInstanceResponse {
    #[serde(rename = "business_id")]
    pub business_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "license_key_id")]
    pub license_key_id: String,
    #[serde(rename = "name")]
    pub name: String,
}

impl LicenseKeyInstanceResponse {
    pub fn new(business_id: String, created_at: String, id: String, license_key_id: String, name: String) -> LicenseKeyInstanceResponse {
        LicenseKeyInstanceResponse {
            business_id,
            created_at,
            id,
            license_key_id,
            name,
        }
    }
}

