/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicenseKeyDuration {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "interval")]
    pub interval: models::TimeInterval,
}

impl LicenseKeyDuration {
    pub fn new(count: i32, interval: models::TimeInterval) -> LicenseKeyDuration {
        LicenseKeyDuration {
            count,
            interval,
        }
    }
}

