/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LineItemSummary {
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "customer_credits")]
    pub customer_credits: i64,
    #[serde(rename = "settlement_amount")]
    pub settlement_amount: i32,
    #[serde(rename = "settlement_currency")]
    pub settlement_currency: models::Currency,
    #[serde(rename = "settlement_tax", skip_serializing_if = "Option::is_none")]
    pub settlement_tax: Option<i32>,
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<i32>,
    #[serde(rename = "total_amount")]
    pub total_amount: i32,
}

impl LineItemSummary {
    pub fn new(currency: models::Currency, customer_credits: i64, settlement_amount: i32, settlement_currency: models::Currency, total_amount: i32) -> LineItemSummary {
        LineItemSummary {
            currency,
            customer_credits,
            settlement_amount,
            settlement_currency,
            settlement_tax: None,
            tax: None,
            total_amount,
        }
    }
}

