/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListBrandsResponse {
    /// List of brands for this business
    #[serde(rename = "items")]
    pub items: Vec<models::BrandResponse>,
}

impl ListBrandsResponse {
    pub fn new(items: Vec<models::BrandResponse>) -> ListBrandsResponse {
        ListBrandsResponse {
            items,
        }
    }
}

