/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListUsageHistoryQueryParams {
    /// Filter by end date (inclusive)
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// Filter by specific meter ID
    #[serde(rename = "meter_id", skip_serializing_if = "Option::is_none")]
    pub meter_id: Option<String>,
    /// Page number (default: 0)
    #[serde(rename = "page_number", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    /// Page size (default: 10, max: 100)
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    /// Filter by start date (inclusive)
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
}

impl ListUsageHistoryQueryParams {
    pub fn new() -> ListUsageHistoryQueryParams {
        ListUsageHistoryQueryParams {
            end_date: None,
            meter_id: None,
            page_number: None,
            page_size: None,
            start_date: None,
        }
    }
}

