/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListProductCollectionsQueryParams {
    /// List archived collections
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
    /// Filter by Brand id
    #[serde(rename = "brand_id", skip_serializing_if = "Option::is_none")]
    pub brand_id: Option<String>,
    /// Page number default is 0
    #[serde(rename = "page_number", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    /// Page size default is 10 max is 100
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
}

impl ListProductCollectionsQueryParams {
    pub fn new() -> ListProductCollectionsQueryParams {
        ListProductCollectionsQueryParams {
            archived: None,
            brand_id: None,
            page_number: None,
            page_size: None,
        }
    }
}

