/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEntitlementGrantsResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::EntitlementGrantResponse>,
}

impl ListEntitlementGrantsResponse {
    pub fn new(items: Vec<models::EntitlementGrantResponse>) -> ListEntitlementGrantsResponse {
        ListEntitlementGrantsResponse {
            items,
        }
    }
}

