/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListWebhooksResponse {
    /// List of webhoooks
    #[serde(rename = "data")]
    pub data: Vec<models::WebhookDetails>,
    /// true if no more values are to be fetched.
    #[serde(rename = "done")]
    pub done: bool,
    /// Cursor pointing to the next paginated object
    #[serde(rename = "iterator", skip_serializing_if = "Option::is_none")]
    pub iterator: Option<String>,
    /// Cursor pointing to the previous paginated object
    #[serde(rename = "prev_iterator", skip_serializing_if = "Option::is_none")]
    pub prev_iterator: Option<String>,
}

impl ListWebhooksResponse {
    pub fn new(data: Vec<models::WebhookDetails>, done: bool) -> ListWebhooksResponse {
        ListWebhooksResponse {
            data,
            done,
            iterator: None,
            prev_iterator: None,
        }
    }
}

