/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDisputeResponse {
    /// The amount involved in the dispute, represented as a string to accommodate precision.
    #[serde(rename = "amount")]
    pub amount: String,
    /// The unique identifier of the business involved in the dispute.
    #[serde(rename = "business_id")]
    pub business_id: String,
    /// The timestamp of when the dispute was created, in UTC.
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// The currency of the disputed amount, represented as an ISO 4217 currency code.
    #[serde(rename = "currency")]
    pub currency: String,
    /// The unique identifier of the dispute.
    #[serde(rename = "dispute_id")]
    pub dispute_id: String,
    /// The current stage of the dispute process.
    #[serde(rename = "dispute_stage")]
    pub dispute_stage: models::DisputeStage,
    /// The current status of the dispute.
    #[serde(rename = "dispute_status")]
    pub dispute_status: models::DisputeStatus,
    /// The unique identifier of the payment associated with the dispute.
    #[serde(rename = "payment_id")]
    pub payment_id: String,
}

impl ListDisputeResponse {
    pub fn new(amount: String, business_id: String, created_at: String, currency: String, dispute_id: String, dispute_stage: models::DisputeStage, dispute_status: models::DisputeStatus, payment_id: String) -> ListDisputeResponse {
        ListDisputeResponse {
            amount,
            business_id,
            created_at,
            currency,
            dispute_id,
            dispute_stage,
            dispute_status,
            payment_id,
        }
    }
}

