/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeterCartResponseItem : Response struct representing usage-based meter cart details for a subscription
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterCartResponseItem {
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "free_threshold")]
    pub free_threshold: i64,
    #[serde(rename = "measurement_unit")]
    pub measurement_unit: String,
    #[serde(rename = "meter_id")]
    pub meter_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "price_per_unit", skip_serializing_if = "Option::is_none")]
    pub price_per_unit: Option<String>,
}

impl MeterCartResponseItem {
    /// Response struct representing usage-based meter cart details for a subscription
    pub fn new(currency: models::Currency, free_threshold: i64, measurement_unit: String, meter_id: String, name: String) -> MeterCartResponseItem {
        MeterCartResponseItem {
            currency,
            description: None,
            free_threshold,
            measurement_unit,
            meter_id,
            name,
            price_per_unit: None,
        }
    }
}

