/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeterFilter1 : Level 1 nested filter - can contain Level 2 filters
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterFilter1 {
    #[serde(rename = "clauses")]
    pub clauses: Box<models::Level1Clause>,
    #[serde(rename = "conjunction")]
    pub conjunction: models::Conjunction,
}

impl MeterFilter1 {
    /// Level 1 nested filter - can contain Level 2 filters
    pub fn new(clauses: models::Level1Clause, conjunction: models::Conjunction) -> MeterFilter1 {
        MeterFilter1 {
            clauses: Box::new(clauses),
            conjunction,
        }
    }
}

