/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterAggregation {
    /// Required when type is not COUNT
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Aggregation type for the meter
    #[serde(rename = "type")]
    pub r#type: models::AggregationType,
}

impl MeterAggregation {
    pub fn new(r#type: models::AggregationType) -> MeterAggregation {
        MeterAggregation {
            key: None,
            r#type,
        }
    }
}

