/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeterCreditEntitlementCartResponse : Response struct representing meter-credit entitlement mapping cart details for a subscription
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterCreditEntitlementCartResponse {
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    #[serde(rename = "meter_id")]
    pub meter_id: String,
    #[serde(rename = "meter_name")]
    pub meter_name: String,
    #[serde(rename = "meter_units_per_credit")]
    pub meter_units_per_credit: String,
    #[serde(rename = "product_id")]
    pub product_id: String,
}

impl MeterCreditEntitlementCartResponse {
    /// Response struct representing meter-credit entitlement mapping cart details for a subscription
    pub fn new(credit_entitlement_id: String, meter_id: String, meter_name: String, meter_units_per_credit: String, product_id: String) -> MeterCreditEntitlementCartResponse {
        MeterCreditEntitlementCartResponse {
            credit_entitlement_id,
            meter_id,
            meter_name,
            meter_units_per_credit,
            product_id,
        }
    }
}

