/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeterFilterCondition : Filter condition with key, operator, and value
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterFilterCondition {
    /// Filter key to apply
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "operator")]
    pub operator: models::FilterOperator,
    #[serde(rename = "value")]
    pub value: Box<models::FilterValue>,
}

impl MeterFilterCondition {
    /// Filter condition with key, operator, and value
    pub fn new(key: String, operator: models::FilterOperator, value: models::FilterValue) -> MeterFilterCondition {
        MeterFilterCondition {
            key,
            operator,
            value: Box::new(value),
        }
    }
}

