/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MeterFilter : A filter structure that combines multiple conditions with logical conjunctions (AND/OR).  Supports up to 3 levels of nesting to create complex filter expressions. Each filter has a conjunction (and/or) and clauses that can be either direct conditions or nested filters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterFilter {
    /// Filter clauses - can be direct conditions or nested filters (up to 3 levels deep)
    #[serde(rename = "clauses")]
    pub clauses: Box<models::FilterType>,
    /// Logical conjunction to apply between clauses (and/or)
    #[serde(rename = "conjunction")]
    pub conjunction: models::Conjunction,
}

impl MeterFilter {
    /// A filter structure that combines multiple conditions with logical conjunctions (AND/OR).  Supports up to 3 levels of nesting to create complex filter expressions. Each filter has a conjunction (and/or) and clauses that can be either direct conditions or nested filters.
    pub fn new(clauses: models::FilterType, conjunction: models::Conjunction) -> MeterFilter {
        MeterFilter {
            clauses: Box::new(clauses),
            conjunction,
        }
    }
}

