/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeterResponse {
    #[serde(rename = "aggregation")]
    pub aggregation: Box<models::MeterAggregation>,
    #[serde(rename = "business_id")]
    pub business_id: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "event_name")]
    pub event_name: String,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::MeterFilter>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "measurement_unit")]
    pub measurement_unit: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl MeterResponse {
    pub fn new(aggregation: models::MeterAggregation, business_id: String, created_at: String, event_name: String, id: String, measurement_unit: String, name: String, updated_at: String) -> MeterResponse {
        MeterResponse {
            aggregation: Box::new(aggregation),
            business_id,
            created_at,
            description: None,
            event_name,
            filter: None,
            id,
            measurement_unit,
            name,
            updated_at,
        }
    }
}

