/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewCustomer {
    /// Email is required for creating a new customer
    #[serde(rename = "email")]
    pub email: String,
    /// Optional full name of the customer. If provided during session creation, it is persisted and becomes immutable for the session. If omitted here, it can be provided later via the confirm API.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "phone_number", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
}

impl NewCustomer {
    pub fn new(email: String) -> NewCustomer {
        NewCustomer {
            email,
            name: None,
            phone_number: None,
        }
    }
}

