/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotionConfig {
    /// Notion template identifier to grant access to.
    #[serde(rename = "notion_template_id")]
    pub notion_template_id: String,
}

impl NotionConfig {
    pub fn new(notion_template_id: String) -> NotionConfig {
        NotionConfig {
            notion_template_id,
        }
    }
}

