/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnPaymentFailure : Specifies how to handle subscription plan changes when payment fails.  This enum controls whether the subscription should be updated immediately or only after payment succeeds.
/// Specifies how to handle subscription plan changes when payment fails.  This enum controls whether the subscription should be updated immediately or only after payment succeeds.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnPaymentFailure {
    #[serde(rename = "prevent_change")]
    PreventChange,
    #[serde(rename = "apply_change")]
    ApplyChange,

}

impl std::fmt::Display for OnPaymentFailure {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::PreventChange => write!(f, "prevent_change"),
            Self::ApplyChange => write!(f, "apply_change"),
        }
    }
}

impl Default for OnPaymentFailure {
    fn default() -> OnPaymentFailure {
        Self::PreventChange
    }
}

