/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OneTimeProductCartItemResponse {
    #[serde(rename = "product_id")]
    pub product_id: String,
    #[serde(rename = "quantity")]
    pub quantity: i32,
}

impl OneTimeProductCartItemResponse {
    pub fn new(product_id: String, quantity: i32) -> OneTimeProductCartItemResponse {
        OneTimeProductCartItemResponse {
            product_id,
            quantity,
        }
    }
}

