/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OutgoingWebhookData {
    Payment(Box<models::Payment>),
    Subscription1(Box<models::Subscription1>),
    Refund(Box<models::Refund>),
    Dispute(Box<models::Dispute>),
    LicenseKey(Box<models::LicenseKey>),
    CreditLedgerEntry(Box<models::CreditLedgerEntry>),
    CreditBalanceLow(Box<models::CreditBalanceLow>),
}

impl Default for OutgoingWebhookData {
    fn default() -> Self {
        Self::Payment(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayloadType {
    #[serde(rename = "CreditBalanceLow")]
    CreditBalanceLow,
}

impl Default for PayloadType {
    fn default() -> PayloadType {
        Self::CreditBalanceLow
    }
}

