/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchAddonRequest {
    /// The currency of the Addon
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
    /// Description of the Addon, optional and must be at most 1000 characters.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Addon image id after its uploaded to S3
    #[serde(rename = "image_id", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<uuid::Uuid>,
    /// Name of the Addon, optional and must be at most 100 characters.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Amount of the addon
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    /// Tax category of the Addon.
    #[serde(rename = "tax_category", skip_serializing_if = "Option::is_none")]
    pub tax_category: Option<models::TaxCategory>,
}

impl PatchAddonRequest {
    pub fn new() -> PatchAddonRequest {
        PatchAddonRequest {
            currency: None,
            description: None,
            image_id: None,
            name: None,
            price: None,
            tax_category: None,
        }
    }
}

