/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchProductCollectionRequest {
    /// Optional brand_id update
    #[serde(rename = "brand_id", skip_serializing_if = "Option::is_none")]
    pub brand_id: Option<String>,
    /// Optional description update - pass null to remove, omit to keep unchanged
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Optional new order for groups (array of group UUIDs in desired order)
    #[serde(rename = "group_order", skip_serializing_if = "Option::is_none")]
    pub group_order: Option<Vec<uuid::Uuid>>,
    /// Optional image update - pass null to remove, omit to keep unchanged
    #[serde(rename = "image_id", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<uuid::Uuid>,
    /// Optional new name for the collection
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl PatchProductCollectionRequest {
    pub fn new() -> PatchProductCollectionRequest {
        PatchProductCollectionRequest {
            brand_id: None,
            description: None,
            group_order: None,
            image_id: None,
            name: None,
        }
    }
}

