/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchLicenseKeyRequest {
    /// The updated activation limit for the license key. Use `null` to remove the limit, or omit this field to leave it unchanged.
    #[serde(rename = "activations_limit", skip_serializing_if = "Option::is_none")]
    pub activations_limit: Option<i32>,
    /// Indicates whether the license key should be disabled. A value of `true` disables the key, while `false` enables it. Omit this field to leave it unchanged.
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// The updated expiration timestamp for the license key in UTC. Use `null` to remove the expiration date, or omit this field to leave it unchanged.
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl PatchLicenseKeyRequest {
    pub fn new() -> PatchLicenseKeyRequest {
        PatchLicenseKeyRequest {
            activations_limit: None,
            disabled: None,
            expires_at: None,
        }
    }
}

