/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchProductCollectionGroupProductRequest {
    /// Status of the product in the group
    #[serde(rename = "status")]
    pub status: bool,
}

impl PatchProductCollectionGroupProductRequest {
    pub fn new(status: bool) -> PatchProductCollectionGroupProductRequest {
        PatchProductCollectionGroupProductRequest {
            status,
        }
    }
}

