/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchCreditEntitlementRequest {
    /// Currency for pricing
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<models::Currency>,
    /// Optional description of the credit entitlement
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Number of days after which credits expire
    #[serde(rename = "expires_after_days", skip_serializing_if = "Option::is_none")]
    pub expires_after_days: Option<i32>,
    /// Maximum number of times credits can be rolled over
    #[serde(rename = "max_rollover_count", skip_serializing_if = "Option::is_none")]
    pub max_rollover_count: Option<i32>,
    /// Name of the credit entitlement
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Controls how overage is handled at billing cycle end.
    #[serde(rename = "overage_behavior", skip_serializing_if = "Option::is_none")]
    pub overage_behavior: Option<models::CbbOverageBehavior>,
    /// Whether overage charges are enabled when credits run out
    #[serde(rename = "overage_enabled", skip_serializing_if = "Option::is_none")]
    pub overage_enabled: Option<bool>,
    /// Maximum overage units allowed
    #[serde(rename = "overage_limit", skip_serializing_if = "Option::is_none")]
    pub overage_limit: Option<i64>,
    /// Price per credit unit
    #[serde(rename = "price_per_unit", skip_serializing_if = "Option::is_none")]
    pub price_per_unit: Option<String>,
    /// Whether rollover is enabled for unused credits
    #[serde(rename = "rollover_enabled", skip_serializing_if = "Option::is_none")]
    pub rollover_enabled: Option<bool>,
    /// Percentage of unused credits that can rollover (0-100)
    #[serde(rename = "rollover_percentage", skip_serializing_if = "Option::is_none")]
    pub rollover_percentage: Option<i32>,
    /// Count of timeframe periods for rollover limit
    #[serde(rename = "rollover_timeframe_count", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_count: Option<i32>,
    /// Interval type for rollover timeframe
    #[serde(rename = "rollover_timeframe_interval", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_interval: Option<models::TimeInterval>,
    /// Unit of measurement for the credit (e.g., \"API Calls\", \"Tokens\", \"Credits\")
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl PatchCreditEntitlementRequest {
    pub fn new() -> PatchCreditEntitlementRequest {
        PatchCreditEntitlementRequest {
            currency: None,
            description: None,
            expires_after_days: None,
            max_rollover_count: None,
            name: None,
            overage_behavior: None,
            overage_enabled: None,
            overage_limit: None,
            price_per_unit: None,
            rollover_enabled: None,
            rollover_percentage: None,
            rollover_timeframe_count: None,
            rollover_timeframe_interval: None,
            unit: None,
        }
    }
}

