/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchProductCollectionGroupRequest {
    /// Optional group name update: Some(Some(name)) = set name, Some(None) = clear name, None = no change
    #[serde(rename = "group_name", skip_serializing_if = "Option::is_none")]
    pub group_name: Option<String>,
    /// Optional new order for products in this group (array of product_collection_group_pdts UUIDs)
    #[serde(rename = "product_order", skip_serializing_if = "Option::is_none")]
    pub product_order: Option<Vec<uuid::Uuid>>,
    /// Optional status update
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<bool>,
}

impl PatchProductCollectionGroupRequest {
    pub fn new() -> PatchProductCollectionGroupRequest {
        PatchProductCollectionGroupRequest {
            group_name: None,
            product_order: None,
            status: None,
        }
    }
}

