/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchBrandRequest {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The UUID you got back from the presigned‐upload call
    #[serde(rename = "image_id", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<uuid::Uuid>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "statement_descriptor", skip_serializing_if = "Option::is_none")]
    pub statement_descriptor: Option<String>,
    #[serde(rename = "support_email", skip_serializing_if = "Option::is_none")]
    pub support_email: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl PatchBrandRequest {
    pub fn new() -> PatchBrandRequest {
        PatchBrandRequest {
            description: None,
            image_id: None,
            name: None,
            statement_descriptor: None,
            support_email: None,
            url: None,
        }
    }
}

