/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentLineItem {
    #[serde(rename = "amount")]
    pub amount: i32,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "items_id")]
    pub items_id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "refundable_amount")]
    pub refundable_amount: i32,
    #[serde(rename = "tax")]
    pub tax: i32,
}

impl PaymentLineItem {
    pub fn new(amount: i32, items_id: String, refundable_amount: i32, tax: i32) -> PaymentLineItem {
        PaymentLineItem {
            amount,
            description: None,
            items_id,
            name: None,
            refundable_amount,
            tax,
        }
    }
}

