/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentLineItemsResponse {
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "items")]
    pub items: Vec<models::PaymentLineItem>,
}

impl PaymentLineItemsResponse {
    pub fn new(currency: models::Currency, items: Vec<models::PaymentLineItem>) -> PaymentLineItemsResponse {
        PaymentLineItemsResponse {
            currency,
            items,
        }
    }
}

