/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentMethodTypes {
    #[serde(rename = "ach")]
    Ach,
    #[serde(rename = "affirm")]
    Affirm,
    #[serde(rename = "afterpay_clearpay")]
    AfterpayClearpay,
    #[serde(rename = "alfamart")]
    Alfamart,
    #[serde(rename = "ali_pay")]
    AliPay,
    #[serde(rename = "ali_pay_hk")]
    AliPayHk,
    #[serde(rename = "alma")]
    Alma,
    #[serde(rename = "amazon_pay")]
    AmazonPay,
    #[serde(rename = "apple_pay")]
    ApplePay,
    #[serde(rename = "atome")]
    Atome,
    #[serde(rename = "bacs")]
    Bacs,
    #[serde(rename = "bancontact_card")]
    BancontactCard,
    #[serde(rename = "becs")]
    Becs,
    #[serde(rename = "benefit")]
    Benefit,
    #[serde(rename = "bizum")]
    Bizum,
    #[serde(rename = "blik")]
    Blik,
    #[serde(rename = "boleto")]
    Boleto,
    #[serde(rename = "bca_bank_transfer")]
    BcaBankTransfer,
    #[serde(rename = "bni_va")]
    BniVa,
    #[serde(rename = "bri_va")]
    BriVa,
    #[serde(rename = "card_redirect")]
    CardRedirect,
    #[serde(rename = "cimb_va")]
    CimbVa,
    #[serde(rename = "classic")]
    Classic,
    #[serde(rename = "credit")]
    Credit,
    #[serde(rename = "crypto_currency")]
    CryptoCurrency,
    #[serde(rename = "cashapp")]
    Cashapp,
    #[serde(rename = "dana")]
    Dana,
    #[serde(rename = "danamon_va")]
    DanamonVa,
    #[serde(rename = "debit")]
    Debit,
    #[serde(rename = "duit_now")]
    DuitNow,
    #[serde(rename = "efecty")]
    Efecty,
    #[serde(rename = "eft")]
    Eft,
    #[serde(rename = "eps")]
    Eps,
    #[serde(rename = "fps")]
    Fps,
    #[serde(rename = "evoucher")]
    Evoucher,
    #[serde(rename = "giropay")]
    Giropay,
    #[serde(rename = "givex")]
    Givex,
    #[serde(rename = "google_pay")]
    GooglePay,
    #[serde(rename = "go_pay")]
    GoPay,
    #[serde(rename = "gcash")]
    Gcash,
    #[serde(rename = "ideal")]
    Ideal,
    #[serde(rename = "interac")]
    Interac,
    #[serde(rename = "indomaret")]
    Indomaret,
    #[serde(rename = "klarna")]
    Klarna,
    #[serde(rename = "kakao_pay")]
    KakaoPay,
    #[serde(rename = "local_bank_redirect")]
    LocalBankRedirect,
    #[serde(rename = "mandiri_va")]
    MandiriVa,
    #[serde(rename = "knet")]
    Knet,
    #[serde(rename = "mb_way")]
    MbWay,
    #[serde(rename = "mobile_pay")]
    MobilePay,
    #[serde(rename = "momo")]
    Momo,
    #[serde(rename = "momo_atm")]
    MomoAtm,
    #[serde(rename = "multibanco")]
    Multibanco,
    #[serde(rename = "online_banking_thailand")]
    OnlineBankingThailand,
    #[serde(rename = "online_banking_czech_republic")]
    OnlineBankingCzechRepublic,
    #[serde(rename = "online_banking_finland")]
    OnlineBankingFinland,
    #[serde(rename = "online_banking_fpx")]
    OnlineBankingFpx,
    #[serde(rename = "online_banking_poland")]
    OnlineBankingPoland,
    #[serde(rename = "online_banking_slovakia")]
    OnlineBankingSlovakia,
    #[serde(rename = "oxxo")]
    Oxxo,
    #[serde(rename = "pago_efectivo")]
    PagoEfectivo,
    #[serde(rename = "permata_bank_transfer")]
    PermataBankTransfer,
    #[serde(rename = "open_banking_uk")]
    OpenBankingUk,
    #[serde(rename = "pay_bright")]
    PayBright,
    #[serde(rename = "paypal")]
    Paypal,
    #[serde(rename = "paze")]
    Paze,
    #[serde(rename = "pix")]
    Pix,
    #[serde(rename = "pay_safe_card")]
    PaySafeCard,
    #[serde(rename = "przelewy24")]
    Przelewy24,
    #[serde(rename = "prompt_pay")]
    PromptPay,
    #[serde(rename = "pse")]
    Pse,
    #[serde(rename = "red_compra")]
    RedCompra,
    #[serde(rename = "red_pagos")]
    RedPagos,
    #[serde(rename = "samsung_pay")]
    SamsungPay,
    #[serde(rename = "sepa")]
    Sepa,
    #[serde(rename = "sepa_bank_transfer")]
    SepaBankTransfer,
    #[serde(rename = "sofort")]
    Sofort,
    #[serde(rename = "swish")]
    Swish,
    #[serde(rename = "touch_n_go")]
    TouchNGo,
    #[serde(rename = "trustly")]
    Trustly,
    #[serde(rename = "twint")]
    Twint,
    #[serde(rename = "upi_collect")]
    UpiCollect,
    #[serde(rename = "upi_intent")]
    UpiIntent,
    #[serde(rename = "vipps")]
    Vipps,
    #[serde(rename = "viet_qr")]
    VietQr,
    #[serde(rename = "venmo")]
    Venmo,
    #[serde(rename = "walley")]
    Walley,
    #[serde(rename = "we_chat_pay")]
    WeChatPay,
    #[serde(rename = "seven_eleven")]
    SevenEleven,
    #[serde(rename = "lawson")]
    Lawson,
    #[serde(rename = "mini_stop")]
    MiniStop,
    #[serde(rename = "family_mart")]
    FamilyMart,
    #[serde(rename = "seicomart")]
    Seicomart,
    #[serde(rename = "pay_easy")]
    PayEasy,
    #[serde(rename = "local_bank_transfer")]
    LocalBankTransfer,
    #[serde(rename = "mifinity")]
    Mifinity,
    #[serde(rename = "open_banking_pis")]
    OpenBankingPis,
    #[serde(rename = "direct_carrier_billing")]
    DirectCarrierBilling,
    #[serde(rename = "instant_bank_transfer")]
    InstantBankTransfer,
    #[serde(rename = "billie")]
    Billie,
    #[serde(rename = "zip")]
    Zip,
    #[serde(rename = "revolut_pay")]
    RevolutPay,
    #[serde(rename = "naver_pay")]
    NaverPay,
    #[serde(rename = "payco")]
    Payco,

}

impl std::fmt::Display for PaymentMethodTypes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ach => write!(f, "ach"),
            Self::Affirm => write!(f, "affirm"),
            Self::AfterpayClearpay => write!(f, "afterpay_clearpay"),
            Self::Alfamart => write!(f, "alfamart"),
            Self::AliPay => write!(f, "ali_pay"),
            Self::AliPayHk => write!(f, "ali_pay_hk"),
            Self::Alma => write!(f, "alma"),
            Self::AmazonPay => write!(f, "amazon_pay"),
            Self::ApplePay => write!(f, "apple_pay"),
            Self::Atome => write!(f, "atome"),
            Self::Bacs => write!(f, "bacs"),
            Self::BancontactCard => write!(f, "bancontact_card"),
            Self::Becs => write!(f, "becs"),
            Self::Benefit => write!(f, "benefit"),
            Self::Bizum => write!(f, "bizum"),
            Self::Blik => write!(f, "blik"),
            Self::Boleto => write!(f, "boleto"),
            Self::BcaBankTransfer => write!(f, "bca_bank_transfer"),
            Self::BniVa => write!(f, "bni_va"),
            Self::BriVa => write!(f, "bri_va"),
            Self::CardRedirect => write!(f, "card_redirect"),
            Self::CimbVa => write!(f, "cimb_va"),
            Self::Classic => write!(f, "classic"),
            Self::Credit => write!(f, "credit"),
            Self::CryptoCurrency => write!(f, "crypto_currency"),
            Self::Cashapp => write!(f, "cashapp"),
            Self::Dana => write!(f, "dana"),
            Self::DanamonVa => write!(f, "danamon_va"),
            Self::Debit => write!(f, "debit"),
            Self::DuitNow => write!(f, "duit_now"),
            Self::Efecty => write!(f, "efecty"),
            Self::Eft => write!(f, "eft"),
            Self::Eps => write!(f, "eps"),
            Self::Fps => write!(f, "fps"),
            Self::Evoucher => write!(f, "evoucher"),
            Self::Giropay => write!(f, "giropay"),
            Self::Givex => write!(f, "givex"),
            Self::GooglePay => write!(f, "google_pay"),
            Self::GoPay => write!(f, "go_pay"),
            Self::Gcash => write!(f, "gcash"),
            Self::Ideal => write!(f, "ideal"),
            Self::Interac => write!(f, "interac"),
            Self::Indomaret => write!(f, "indomaret"),
            Self::Klarna => write!(f, "klarna"),
            Self::KakaoPay => write!(f, "kakao_pay"),
            Self::LocalBankRedirect => write!(f, "local_bank_redirect"),
            Self::MandiriVa => write!(f, "mandiri_va"),
            Self::Knet => write!(f, "knet"),
            Self::MbWay => write!(f, "mb_way"),
            Self::MobilePay => write!(f, "mobile_pay"),
            Self::Momo => write!(f, "momo"),
            Self::MomoAtm => write!(f, "momo_atm"),
            Self::Multibanco => write!(f, "multibanco"),
            Self::OnlineBankingThailand => write!(f, "online_banking_thailand"),
            Self::OnlineBankingCzechRepublic => write!(f, "online_banking_czech_republic"),
            Self::OnlineBankingFinland => write!(f, "online_banking_finland"),
            Self::OnlineBankingFpx => write!(f, "online_banking_fpx"),
            Self::OnlineBankingPoland => write!(f, "online_banking_poland"),
            Self::OnlineBankingSlovakia => write!(f, "online_banking_slovakia"),
            Self::Oxxo => write!(f, "oxxo"),
            Self::PagoEfectivo => write!(f, "pago_efectivo"),
            Self::PermataBankTransfer => write!(f, "permata_bank_transfer"),
            Self::OpenBankingUk => write!(f, "open_banking_uk"),
            Self::PayBright => write!(f, "pay_bright"),
            Self::Paypal => write!(f, "paypal"),
            Self::Paze => write!(f, "paze"),
            Self::Pix => write!(f, "pix"),
            Self::PaySafeCard => write!(f, "pay_safe_card"),
            Self::Przelewy24 => write!(f, "przelewy24"),
            Self::PromptPay => write!(f, "prompt_pay"),
            Self::Pse => write!(f, "pse"),
            Self::RedCompra => write!(f, "red_compra"),
            Self::RedPagos => write!(f, "red_pagos"),
            Self::SamsungPay => write!(f, "samsung_pay"),
            Self::Sepa => write!(f, "sepa"),
            Self::SepaBankTransfer => write!(f, "sepa_bank_transfer"),
            Self::Sofort => write!(f, "sofort"),
            Self::Swish => write!(f, "swish"),
            Self::TouchNGo => write!(f, "touch_n_go"),
            Self::Trustly => write!(f, "trustly"),
            Self::Twint => write!(f, "twint"),
            Self::UpiCollect => write!(f, "upi_collect"),
            Self::UpiIntent => write!(f, "upi_intent"),
            Self::Vipps => write!(f, "vipps"),
            Self::VietQr => write!(f, "viet_qr"),
            Self::Venmo => write!(f, "venmo"),
            Self::Walley => write!(f, "walley"),
            Self::WeChatPay => write!(f, "we_chat_pay"),
            Self::SevenEleven => write!(f, "seven_eleven"),
            Self::Lawson => write!(f, "lawson"),
            Self::MiniStop => write!(f, "mini_stop"),
            Self::FamilyMart => write!(f, "family_mart"),
            Self::Seicomart => write!(f, "seicomart"),
            Self::PayEasy => write!(f, "pay_easy"),
            Self::LocalBankTransfer => write!(f, "local_bank_transfer"),
            Self::Mifinity => write!(f, "mifinity"),
            Self::OpenBankingPis => write!(f, "open_banking_pis"),
            Self::DirectCarrierBilling => write!(f, "direct_carrier_billing"),
            Self::InstantBankTransfer => write!(f, "instant_bank_transfer"),
            Self::Billie => write!(f, "billie"),
            Self::Zip => write!(f, "zip"),
            Self::RevolutPay => write!(f, "revolut_pay"),
            Self::NaverPay => write!(f, "naver_pay"),
            Self::Payco => write!(f, "payco"),
        }
    }
}

impl Default for PaymentMethodTypes {
    fn default() -> PaymentMethodTypes {
        Self::Ach
    }
}

