/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PayoutStatus {
    #[serde(rename = "not_initiated")]
    NotInitiated,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "on_hold")]
    OnHold,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "success")]
    Success,

}

impl std::fmt::Display for PayoutStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NotInitiated => write!(f, "not_initiated"),
            Self::InProgress => write!(f, "in_progress"),
            Self::OnHold => write!(f, "on_hold"),
            Self::Failed => write!(f, "failed"),
            Self::Success => write!(f, "success"),
        }
    }
}

impl Default for PayoutStatus {
    fn default() -> PayoutStatus {
        Self::NotInitiated
    }
}

