/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCollectionListItem {
    /// Timestamp when created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Collection description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Collection ID
    #[serde(rename = "id")]
    pub id: String,
    /// Collection image URL
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Collection name
    #[serde(rename = "name")]
    pub name: String,
    /// Number of products in the collection
    #[serde(rename = "products_count")]
    pub products_count: i64,
    /// Timestamp when last updated
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ProductCollectionListItem {
    pub fn new(created_at: String, id: String, name: String, products_count: i64, updated_at: String) -> ProductCollectionListItem {
        ProductCollectionListItem {
            created_at,
            description: None,
            id,
            image: None,
            name,
            products_count,
            updated_at,
        }
    }
}

