/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductCollectionResponse {
    /// Brand ID for the collection
    #[serde(rename = "brand_id")]
    pub brand_id: String,
    /// Timestamp when the collection was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Description of the collection
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Groups in this collection
    #[serde(rename = "groups")]
    pub groups: Vec<models::ProductCollectionGroupResponse>,
    /// Unique identifier for the product collection
    #[serde(rename = "id")]
    pub id: String,
    /// URL of the collection image
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Name of the collection
    #[serde(rename = "name")]
    pub name: String,
    /// Timestamp when the collection was last updated
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ProductCollectionResponse {
    pub fn new(brand_id: String, created_at: String, groups: Vec<models::ProductCollectionGroupResponse>, id: String, name: String, updated_at: String) -> ProductCollectionResponse {
        ProductCollectionResponse {
            brand_id,
            created_at,
            description: None,
            groups,
            id,
            image: None,
            name,
            updated_at,
        }
    }
}

