/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProrationBillingMode {
    #[serde(rename = "prorated_immediately")]
    ProratedImmediately,
    #[serde(rename = "full_immediately")]
    FullImmediately,
    #[serde(rename = "difference_immediately")]
    DifferenceImmediately,

}

impl std::fmt::Display for ProrationBillingMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ProratedImmediately => write!(f, "prorated_immediately"),
            Self::FullImmediately => write!(f, "full_immediately"),
            Self::DifferenceImmediately => write!(f, "difference_immediately"),
        }
    }
}

impl Default for ProrationBillingMode {
    fn default() -> ProrationBillingMode {
        Self::ProratedImmediately
    }
}

