/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecurringBreakup : Breakup of recurring payments (subscription only)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurringBreakup {
    /// Total discount amount
    #[serde(rename = "discount")]
    pub discount: i32,
    /// Subtotal before discount (pre-tax original prices)
    #[serde(rename = "subtotal")]
    pub subtotal: i32,
    /// Total tax on recurring payments
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<i32>,
    /// Total recurring amount including tax
    #[serde(rename = "total_amount")]
    pub total_amount: i32,
}

impl RecurringBreakup {
    /// Breakup of recurring payments (subscription only)
    pub fn new(discount: i32, subtotal: i32, total_amount: i32) -> RecurringBreakup {
        RecurringBreakup {
            discount,
            subtotal,
            tax: None,
            total_amount,
        }
    }
}

