/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ResolvedDigitalFiles : Populated digital-files payload on entitlement read responses. Each file carries a short-lived presigned download URL.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResolvedDigitalFiles {
    /// Optional external URL, passed through from the entitlement configuration.
    #[serde(rename = "external_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_url: Option<Option<String>>,
    /// One entry per attached file.
    #[serde(rename = "files")]
    pub files: Vec<models::ResolvedDigitalFile>,
    /// Optional human-readable delivery instructions, passed through from the entitlement configuration.
    #[serde(rename = "instructions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<Option<String>>,
}

impl ResolvedDigitalFiles {
    /// Populated digital-files payload on entitlement read responses. Each file carries a short-lived presigned download URL.
    pub fn new(files: Vec<models::ResolvedDigitalFile>) -> ResolvedDigitalFiles {
        ResolvedDigitalFiles {
            external_url: None,
            files,
            instructions: None,
        }
    }
}

