/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShortLinkResponse {
    /// Full URL.
    #[serde(rename = "full_url")]
    pub full_url: String,
    /// Short URL.
    #[serde(rename = "short_url")]
    pub short_url: String,
}

impl ShortLinkResponse {
    pub fn new(full_url: String, short_url: String) -> ShortLinkResponse {
        ShortLinkResponse {
            full_url,
            short_url,
        }
    }
}

