/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShortLinkItem {
    /// When the short url was created
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Full URL the short url redirects to
    #[serde(rename = "full_url")]
    pub full_url: String,
    /// Product ID associated with the short link
    #[serde(rename = "product_id")]
    pub product_id: String,
    /// Short URL
    #[serde(rename = "short_url")]
    pub short_url: String,
}

impl ShortLinkItem {
    pub fn new(created_at: String, full_url: String, product_id: String, short_url: String) -> ShortLinkItem {
        ShortLinkItem {
            created_at,
            full_url,
            product_id,
            short_url,
        }
    }
}

