/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionData {
    #[serde(rename = "on_demand", skip_serializing_if = "Option::is_none")]
    pub on_demand: Option<Box<models::OnDemandSubscriptionReq>>,
    /// Optional trial period in days If specified, this value overrides the trial period set in the product's price Must be between 0 and 10000 days
    #[serde(rename = "trial_period_days", skip_serializing_if = "Option::is_none")]
    pub trial_period_days: Option<i32>,
}

impl SubscriptionData {
    pub fn new() -> SubscriptionData {
        SubscriptionData {
            on_demand: None,
            trial_period_days: None,
        }
    }
}

