/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscription {
    #[serde(rename = "currency")]
    pub currency: models::Currency,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "product_id")]
    pub product_id: String,
    #[serde(rename = "proration_factor")]
    pub proration_factor: f64,
    #[serde(rename = "quantity")]
    pub quantity: i32,
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<i32>,
    #[serde(rename = "tax_inclusive")]
    pub tax_inclusive: bool,
    #[serde(rename = "tax_rate", skip_serializing_if = "Option::is_none")]
    pub tax_rate: Option<f32>,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "unit_price")]
    pub unit_price: i32,
}

impl Subscription {
    pub fn new(currency: models::Currency, id: String, product_id: String, proration_factor: f64, quantity: i32, tax_inclusive: bool, r#type: Type, unit_price: i32) -> Subscription {
        Subscription {
            currency,
            description: None,
            id,
            name: None,
            product_id,
            proration_factor,
            quantity,
            tax: None,
            tax_inclusive,
            tax_rate: None,
            r#type,
            unit_price,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "subscription")]
    Subscription,
}

impl Default for Type {
    fn default() -> Type {
        Self::Subscription
    }
}

