/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubscriptionCreditUsageResponse : Credit usage status for all entitlements linked to a subscription
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionCreditUsageResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::CreditEntitlementUsageStatus>,
    #[serde(rename = "subscription_id")]
    pub subscription_id: String,
}

impl SubscriptionCreditUsageResponse {
    /// Credit usage status for all entitlements linked to a subscription
    pub fn new(items: Vec<models::CreditEntitlementUsageStatus>, subscription_id: String) -> SubscriptionCreditUsageResponse {
        SubscriptionCreditUsageResponse {
            items,
            subscription_id,
        }
    }
}

