/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.97.5
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TelegramConfig {
    /// Telegram chat ID. For groups this is typically a negative integer.
    #[serde(rename = "chat_id")]
    pub chat_id: String,
}

impl TelegramConfig {
    pub fn new(chat_id: String) -> TelegramConfig {
        TelegramConfig {
            chat_id,
        }
    }
}

