/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UndeleteCollectionResponse {
    /// Collection ID that was unarchived
    #[serde(rename = "collection_id")]
    pub collection_id: String,
    /// Product IDs that were excluded because they are archived
    #[serde(rename = "excluded_product_ids")]
    pub excluded_product_ids: Vec<String>,
    /// Success message
    #[serde(rename = "message")]
    pub message: String,
}

impl UndeleteCollectionResponse {
    pub fn new(collection_id: String, excluded_product_ids: Vec<String>, message: String) -> UndeleteCollectionResponse {
        UndeleteCollectionResponse {
            collection_id,
            excluded_product_ids,
            message,
        }
    }
}

