/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdatePaymentMethodReq {
    New(Box<models::New>),
    Existing(Box<models::Existing>),
}

impl Default for UpdatePaymentMethodReq {
    fn default() -> Self {
        Self::New(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "existing")]
    Existing,
}

impl Default for Type {
    fn default() -> Type {
        Self::New
    }
}

