/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateProductImageResponse {
    #[serde(rename = "image_id", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<uuid::Uuid>,
    #[serde(rename = "url")]
    pub url: String,
}

impl UpdateProductImageResponse {
    pub fn new(url: String) -> UpdateProductImageResponse {
        UpdateProductImageResponse {
            image_id: None,
            url,
        }
    }
}

