/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAddonImageResponse {
    #[serde(rename = "image_id")]
    pub image_id: uuid::Uuid,
    #[serde(rename = "url")]
    pub url: String,
}

impl UpdateAddonImageResponse {
    pub fn new(image_id: uuid::Uuid, url: String) -> UpdateAddonImageResponse {
        UpdateAddonImageResponse {
            image_id,
            url,
        }
    }
}

