/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBrandImageResponse {
    /// UUID that will be used as the image identifier/key suffix
    #[serde(rename = "image_id")]
    pub image_id: uuid::Uuid,
    /// Presigned URL to upload the image
    #[serde(rename = "url")]
    pub url: String,
}

impl UpdateBrandImageResponse {
    pub fn new(image_id: uuid::Uuid, url: String) -> UpdateBrandImageResponse {
        UpdateBrandImageResponse {
            image_id,
            url,
        }
    }
}

