/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCollectionImageResponse {
    /// Optional image ID (present when force_update is true)
    #[serde(rename = "image_id", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<uuid::Uuid>,
    /// Presigned S3 URL for uploading the image
    #[serde(rename = "url")]
    pub url: String,
}

impl UpdateCollectionImageResponse {
    pub fn new(url: String) -> UpdateCollectionImageResponse {
        UpdateCollectionImageResponse {
            image_id: None,
            url,
        }
    }
}

