/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCreditEntitlementCartItem {
    #[serde(rename = "credit_entitlement_id")]
    pub credit_entitlement_id: String,
    #[serde(rename = "credits_amount", skip_serializing_if = "Option::is_none")]
    pub credits_amount: Option<String>,
    #[serde(rename = "expires_after_days", skip_serializing_if = "Option::is_none")]
    pub expires_after_days: Option<i32>,
    #[serde(rename = "low_balance_threshold_percent", skip_serializing_if = "Option::is_none")]
    pub low_balance_threshold_percent: Option<i32>,
    #[serde(rename = "max_rollover_count", skip_serializing_if = "Option::is_none")]
    pub max_rollover_count: Option<i32>,
    #[serde(rename = "overage_enabled", skip_serializing_if = "Option::is_none")]
    pub overage_enabled: Option<bool>,
    #[serde(rename = "overage_limit", skip_serializing_if = "Option::is_none")]
    pub overage_limit: Option<String>,
    #[serde(rename = "rollover_enabled", skip_serializing_if = "Option::is_none")]
    pub rollover_enabled: Option<bool>,
    #[serde(rename = "rollover_percentage", skip_serializing_if = "Option::is_none")]
    pub rollover_percentage: Option<i32>,
    #[serde(rename = "rollover_timeframe_count", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_count: Option<i32>,
    #[serde(rename = "rollover_timeframe_interval", skip_serializing_if = "Option::is_none")]
    pub rollover_timeframe_interval: Option<models::TimeInterval>,
}

impl UpdateCreditEntitlementCartItem {
    pub fn new(credit_entitlement_id: String) -> UpdateCreditEntitlementCartItem {
        UpdateCreditEntitlementCartItem {
            credit_entitlement_id,
            credits_amount: None,
            expires_after_days: None,
            low_balance_threshold_percent: None,
            max_rollover_count: None,
            overage_enabled: None,
            overage_limit: None,
            rollover_enabled: None,
            rollover_percentage: None,
            rollover_timeframe_count: None,
            rollover_timeframe_interval: None,
        }
    }
}

