/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCollectionImageQueryParams {
    /// If true, generates a new image ID to force cache invalidation
    #[serde(rename = "force_update", skip_serializing_if = "Option::is_none")]
    pub force_update: Option<bool>,
}

impl UpdateCollectionImageQueryParams {
    pub fn new() -> UpdateCollectionImageQueryParams {
        UpdateCollectionImageQueryParams {
            force_update: None,
        }
    }
}

