/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePaymentMethodResponse {
    #[serde(rename = "client_secret", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<String>,
    #[serde(rename = "expires_on", skip_serializing_if = "Option::is_none")]
    pub expires_on: Option<String>,
    #[serde(rename = "payment_id", skip_serializing_if = "Option::is_none")]
    pub payment_id: Option<String>,
    #[serde(rename = "payment_link", skip_serializing_if = "Option::is_none")]
    pub payment_link: Option<String>,
}

impl UpdatePaymentMethodResponse {
    pub fn new() -> UpdatePaymentMethodResponse {
        UpdatePaymentMethodResponse {
            client_secret: None,
            expires_on: None,
            payment_id: None,
            payment_link: None,
        }
    }
}

