/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadProductFile {
    #[serde(rename = "file_name")]
    pub file_name: String,
}

impl UploadProductFile {
    pub fn new(file_name: String) -> UploadProductFile {
        UploadProductFile {
            file_name,
        }
    }
}

