/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageHistoryItem {
    /// End date of the billing period
    #[serde(rename = "end_date")]
    pub end_date: String,
    /// List of meters and their usage for this billing period
    #[serde(rename = "meters")]
    pub meters: Vec<models::MeterUsageItem>,
    /// Start date of the billing period
    #[serde(rename = "start_date")]
    pub start_date: String,
}

impl UsageHistoryItem {
    pub fn new(end_date: String, meters: Vec<models::MeterUsageItem>, start_date: String) -> UsageHistoryItem {
        UsageHistoryItem {
            end_date,
            meters,
            start_date,
        }
    }
}

