/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateLicenseKeyResponse {
    #[serde(rename = "valid")]
    pub valid: bool,
}

impl ValidateLicenseKeyResponse {
    pub fn new(valid: bool) -> ValidateLicenseKeyResponse {
        ValidateLicenseKeyResponse {
            valid,
        }
    }
}

