/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateLicenseKeyRequest {
    #[serde(rename = "license_key")]
    pub license_key: String,
    #[serde(rename = "license_key_instance_id", skip_serializing_if = "Option::is_none")]
    pub license_key_instance_id: Option<String>,
}

impl ValidateLicenseKeyRequest {
    pub fn new(license_key: String) -> ValidateLicenseKeyRequest {
        ValidateLicenseKeyRequest {
            license_key,
            license_key_instance_id: None,
        }
    }
}

