/*
 * public
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookHeadersReq {
    /// Object of header-value pair to update or add
    #[serde(rename = "headers")]
    pub headers: std::collections::HashMap<String, String>,
}

impl WebhookHeadersReq {
    pub fn new(headers: std::collections::HashMap<String, String>) -> WebhookHeadersReq {
        WebhookHeadersReq {
            headers,
        }
    }
}

